#*****************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# rebuild.tcl: Tcl script for re-creating project 'project_1'
#
# Generated by Vivado on Sun Feb 28 13:14:47 CET 2021
# IP Build 3064653 on Wed Nov 18 14:17:31 MST 2020
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (rebuild.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/project_1/project_1.srcs/utils_1/imports/synth_1/minimig_openaars_top.dcp"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/project_1/project_1.srcs/utils_1/imports/impl_1/minimig_openaars_top_routed.dcp"
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/soc/openaars_defines.vh"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/ciaa_ps2keyboard_map.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/minimig_version.vh"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/clock/amiga_clk.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/clock/amiga_clk_xilinx.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/cart.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/ciaa_ps2keyboard.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/sdram/dpram_inf_generic.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/host/hostcache.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/minimig.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/minimig_bankmapper.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/minimig_m68k_bridge.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/minimig_sram_bridge.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/minimig_syscontrol.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/soc/minimig_virtual_top.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/userio.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/userio_osd.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/userio_osd_spi.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/userio_ps2mouse.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/amiga_keyboard.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_pkg.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_aligner_le.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_aligner.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_fetchloadstore.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_decode.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_shifter.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_alu.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_hazard.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_debug.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_cpu.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/debug_virtualjtag.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/debug_fifo_altera.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/debug_bridge_jtag.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fw/ctrl_boot_832/OSDBoot_832_ROM.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/host/832_bridge.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/audio/AudioMix.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/tg68k/TG68K_Pack.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/rtg/VideoStream.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/host/cfide.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/soc/TG68K.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_hamgenerator_ram_mf.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/tg68k/TG68K_ALU.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/tg68k/TG68KdotC_Kernel.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/akiko/akiko.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/akiko/cornerturn.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/soc/minimig_openaars_top.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/adv7511/signal_generator.sv"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/adv7511/pal_to_ddr.sv"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/adv7511/pal_to_hd_upsample.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/mcp23s17/mcp23s17_input.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/adv7511/adv_ddr.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/adv7511/i2c_master.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/i2s_tx.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/mcp23s17/spi_master.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/adv7511/i2c_sender.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/adv7511/bram_tdp.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/sdram/cpu_cache_new.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/sdram/dpram_256x32.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/sdram/dpram_be_1024x32.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/sdram/sdram_ctrl.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_audiodma.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_beamcounter.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_bitplanedma.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_blitter.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_blitter_adrgen.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_blitter_barrelshifter.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_blitter_fill.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_blitter_minterm.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_copper.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_diskdma.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_refresh.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_spritedma.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_audio.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_audio_channel.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_audio_mixer.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_audio_sigmadelta.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_audio_volume.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_floppy.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_floppy_fifo.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_intcontroller.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_uart.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/audio/audiofilter.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_bitplane_shifter.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_bitplanes.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_collision.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_colortable.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_colortable_ram_mf.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_hamgenerator.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_playfields.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_spritepriority.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_sprites.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_sprites_shifter.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/amber.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/ciaa.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/cia_int.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/cia_timera.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/cia_timerb.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/cia_timerd.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/ciab.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/gary.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/gayle_fifo.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/gayle.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/minimig_autoconfig_rom.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/minimig_autoconfig.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/chameleonv1/gen_reset.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/adv7511_video.xdc"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/buttons.xdc"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/floppy.xdc"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/generic.xdc"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/i2s.xdc"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/joystick.xdc"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/leds.xdc"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/pmod.xdc"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/ps2.xdc"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/sd_card.xdc"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/sdram.xdc"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/timing.xdc"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/uart.xdc"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/wizard.xdc"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/bench/ps2mouse/ps2mouse_ctrl.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/bench/ps2mouse/ps2mouse_tb.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/userio_ps2mouse.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/sim/rom-hostcpu-test/memtest_top_tb.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/sim/rom-hostcpu-test/memtest_orig_top_tb.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fw/ctrl_boot_832/OSDBoot_832_ROM.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/host/cfide.vhd"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/sim/hostcpu-i2c-bridge/i2c_bridge_tb.v"
#    "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/adv7511/i2c_master.v"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/project_1/project_1.srcs/utils_1/imports/synth_1/minimig_openaars_top.dcp" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/project_1/project_1.srcs/utils_1/imports/impl_1/minimig_openaars_top_routed.dcp" \
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  set files [list \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/soc/openaars_defines.vh" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/ciaa_ps2keyboard_map.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/minimig_version.vh" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/clock/amiga_clk.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/clock/amiga_clk_xilinx.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/cart.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/ciaa_ps2keyboard.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/sdram/dpram_inf_generic.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/host/hostcache.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/minimig.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/minimig_bankmapper.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/minimig_m68k_bridge.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/minimig_sram_bridge.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/minimig_syscontrol.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/soc/minimig_virtual_top.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/userio.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/userio_osd.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/userio_osd_spi.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/userio_ps2mouse.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/amiga_keyboard.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_pkg.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_aligner_le.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_aligner.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_fetchloadstore.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_decode.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_shifter.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_alu.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_hazard.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_debug.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/eightthirtytwo_cpu.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/debug_virtualjtag.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/debug_fifo_altera.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/EightThirtyTwo/RTL/debug_bridge_jtag.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fw/ctrl_boot_832/OSDBoot_832_ROM.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/host/832_bridge.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/audio/AudioMix.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/tg68k/TG68K_Pack.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/rtg/VideoStream.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/host/cfide.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/soc/TG68K.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_hamgenerator_ram_mf.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/tg68k/TG68K_ALU.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/tg68k/TG68KdotC_Kernel.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/akiko/akiko.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/akiko/cornerturn.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/soc/minimig_openaars_top.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/adv7511/signal_generator.sv" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/adv7511/pal_to_ddr.sv" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/adv7511/pal_to_hd_upsample.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/mcp23s17/mcp23s17_input.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/adv7511/adv_ddr.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/adv7511/i2c_master.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/i2s_tx.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/mcp23s17/spi_master.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/adv7511/i2c_sender.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/adv7511/bram_tdp.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/sdram/cpu_cache_new.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/sdram/dpram_256x32.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/sdram/dpram_be_1024x32.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/sdram/sdram_ctrl.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_audiodma.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_beamcounter.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_bitplanedma.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_blitter.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_blitter_adrgen.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_blitter_barrelshifter.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_blitter_fill.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_blitter_minterm.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_copper.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_diskdma.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_refresh.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus_spritedma.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/agnus.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_audio.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_audio_channel.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_audio_mixer.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_audio_sigmadelta.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_audio_volume.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_floppy.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_floppy_fifo.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_intcontroller.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula_uart.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/audio/audiofilter.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/paula.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_bitplane_shifter.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_bitplanes.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_collision.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_colortable.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_colortable_ram_mf.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_hamgenerator.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_playfields.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_spritepriority.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_sprites.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise_sprites_shifter.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/denise.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/amber.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/ciaa.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/cia_int.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/cia_timera.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/cia_timerb.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/cia_timerd.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/ciab.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/gary.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/gayle_fifo.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/gayle.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/minimig_autoconfig_rom.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/minimig_autoconfig.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/chameleonv1/gen_reset.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/adv7511_video.xdc" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/buttons.xdc" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/floppy.xdc" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/generic.xdc" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/i2s.xdc" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/joystick.xdc" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/leds.xdc" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/pmod.xdc" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/ps2.xdc" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/sd_card.xdc" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/sdram.xdc" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/timing.xdc" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/uart.xdc" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fpga/openaars/aars_v4.0_lite/wizard.xdc" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/bench/ps2mouse/ps2mouse_ctrl.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/bench/ps2mouse/ps2mouse_tb.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/minimig/userio_ps2mouse.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/sim/rom-hostcpu-test/memtest_top_tb.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/sim/rom-hostcpu-test/memtest_orig_top_tb.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/fw/ctrl_boot_832/OSDBoot_832_ROM.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/host/cfide.vhd" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/sim/hostcpu-i2c-bridge/i2c_bridge_tb.v" \
   "/home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/rtl/openaars/adv7511/i2c_master.v" \
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "project_1"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "rebuild.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/project_1"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a100tfgg676-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "corecontainer.enable" -value "1" -objects $obj
set_property -name "default_lib" -value "work" -objects $obj
set_property -name "enable_core_container" -value "1" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7a100tfgg676-2" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "source_mgmt_mode" -value "DisplayOnly" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "2" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "2" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "2" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "2" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "2" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "2" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "2" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "226" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/rtl/soc/openaars_defines.vh"] \
 [file normalize "${origin_dir}/rtl/minimig/ciaa_ps2keyboard_map.v"] \
 [file normalize "${origin_dir}/fpga/openaars/minimig_version.vh"] \
 [file normalize "${origin_dir}/rtl/clock/amiga_clk.v"] \
 [file normalize "${origin_dir}/rtl/clock/amiga_clk_xilinx.v"] \
 [file normalize "${origin_dir}/rtl/minimig/cart.v"] \
 [file normalize "${origin_dir}/rtl/minimig/ciaa_ps2keyboard.v"] \
 [file normalize "${origin_dir}/rtl/sdram/dpram_inf_generic.v"] \
 [file normalize "${origin_dir}/rtl/host/hostcache.v"] \
 [file normalize "${origin_dir}/rtl/minimig/minimig.v"] \
 [file normalize "${origin_dir}/rtl/minimig/minimig_bankmapper.v"] \
 [file normalize "${origin_dir}/rtl/minimig/minimig_m68k_bridge.v"] \
 [file normalize "${origin_dir}/rtl/minimig/minimig_sram_bridge.v"] \
 [file normalize "${origin_dir}/rtl/minimig/minimig_syscontrol.v"] \
 [file normalize "${origin_dir}/rtl/soc/minimig_virtual_top.v"] \
 [file normalize "${origin_dir}/rtl/minimig/userio.v"] \
 [file normalize "${origin_dir}/rtl/minimig/userio_osd.v"] \
 [file normalize "${origin_dir}/rtl/minimig/userio_osd_spi.v"] \
 [file normalize "${origin_dir}/rtl/minimig/userio_ps2mouse.v"] \
 [file normalize "${origin_dir}/rtl/minimig/amiga_keyboard.v"] \
 [file normalize "${origin_dir}/EightThirtyTwo/RTL/eightthirtytwo_pkg.vhd"] \
 [file normalize "${origin_dir}/EightThirtyTwo/RTL/eightthirtytwo_aligner_le.vhd"] \
 [file normalize "${origin_dir}/EightThirtyTwo/RTL/eightthirtytwo_aligner.vhd"] \
 [file normalize "${origin_dir}/EightThirtyTwo/RTL/eightthirtytwo_fetchloadstore.vhd"] \
 [file normalize "${origin_dir}/EightThirtyTwo/RTL/eightthirtytwo_decode.vhd"] \
 [file normalize "${origin_dir}/EightThirtyTwo/RTL/eightthirtytwo_shifter.vhd"] \
 [file normalize "${origin_dir}/EightThirtyTwo/RTL/eightthirtytwo_alu.vhd"] \
 [file normalize "${origin_dir}/EightThirtyTwo/RTL/eightthirtytwo_hazard.vhd"] \
 [file normalize "${origin_dir}/EightThirtyTwo/RTL/eightthirtytwo_debug.vhd"] \
 [file normalize "${origin_dir}/EightThirtyTwo/RTL/eightthirtytwo_cpu.vhd"] \
 [file normalize "${origin_dir}/EightThirtyTwo/RTL/debug_virtualjtag.vhd"] \
 [file normalize "${origin_dir}/EightThirtyTwo/RTL/debug_fifo_altera.vhd"] \
 [file normalize "${origin_dir}/EightThirtyTwo/RTL/debug_bridge_jtag.vhd"] \
 [file normalize "${origin_dir}/fw/ctrl_boot_832/OSDBoot_832_ROM.vhd"] \
 [file normalize "${origin_dir}/rtl/host/832_bridge.vhd"] \
 [file normalize "${origin_dir}/rtl/audio/AudioMix.vhd"] \
 [file normalize "${origin_dir}/rtl/tg68k/TG68K_Pack.vhd"] \
 [file normalize "${origin_dir}/rtl/rtg/VideoStream.vhd"] \
 [file normalize "${origin_dir}/rtl/host/cfide.vhd"] \
 [file normalize "${origin_dir}/rtl/soc/TG68K.vhd"] \
 [file normalize "${origin_dir}/rtl/minimig/denise_hamgenerator_ram_mf.v"] \
 [file normalize "${origin_dir}/rtl/tg68k/TG68K_ALU.vhd"] \
 [file normalize "${origin_dir}/rtl/tg68k/TG68KdotC_Kernel.vhd"] \
 [file normalize "${origin_dir}/rtl/akiko/akiko.vhd"] \
 [file normalize "${origin_dir}/rtl/akiko/cornerturn.vhd"] \
 [file normalize "${origin_dir}/rtl/soc/minimig_openaars_top.v"] \
 [file normalize "${origin_dir}/rtl/openaars/adv7511/signal_generator.sv"] \
 [file normalize "${origin_dir}/rtl/openaars/adv7511/pal_to_ddr.sv"] \
 [file normalize "${origin_dir}/rtl/openaars/adv7511/pal_to_hd_upsample.v"] \
 [file normalize "${origin_dir}/rtl/openaars/mcp23s17/mcp23s17_input.v"] \
 [file normalize "${origin_dir}/rtl/openaars/adv7511/adv_ddr.v"] \
 [file normalize "${origin_dir}/rtl/openaars/adv7511/i2c_master.v"] \
 [file normalize "${origin_dir}/rtl/openaars/i2s_tx.v"] \
 [file normalize "${origin_dir}/rtl/openaars/mcp23s17/spi_master.v"] \
 [file normalize "${origin_dir}/rtl/openaars/adv7511/i2c_sender.vhd"] \
 [file normalize "${origin_dir}/rtl/openaars/adv7511/bram_tdp.v"] \
 [file normalize "${origin_dir}/rtl/sdram/cpu_cache_new.v"] \
 [file normalize "${origin_dir}/rtl/sdram/dpram_256x32.v"] \
 [file normalize "${origin_dir}/rtl/sdram/dpram_be_1024x32.v"] \
 [file normalize "${origin_dir}/rtl/sdram/sdram_ctrl.v"] \
 [file normalize "${origin_dir}/rtl/minimig/agnus_audiodma.v"] \
 [file normalize "${origin_dir}/rtl/minimig/agnus_beamcounter.v"] \
 [file normalize "${origin_dir}/rtl/minimig/agnus_bitplanedma.v"] \
 [file normalize "${origin_dir}/rtl/minimig/agnus_blitter.v"] \
 [file normalize "${origin_dir}/rtl/minimig/agnus_blitter_adrgen.v"] \
 [file normalize "${origin_dir}/rtl/minimig/agnus_blitter_barrelshifter.v"] \
 [file normalize "${origin_dir}/rtl/minimig/agnus_blitter_fill.v"] \
 [file normalize "${origin_dir}/rtl/minimig/agnus_blitter_minterm.v"] \
 [file normalize "${origin_dir}/rtl/minimig/agnus_copper.v"] \
 [file normalize "${origin_dir}/rtl/minimig/agnus_diskdma.v"] \
 [file normalize "${origin_dir}/rtl/minimig/agnus_refresh.v"] \
 [file normalize "${origin_dir}/rtl/minimig/agnus_spritedma.v"] \
 [file normalize "${origin_dir}/rtl/minimig/agnus.v"] \
 [file normalize "${origin_dir}/rtl/minimig/paula_audio.v"] \
 [file normalize "${origin_dir}/rtl/minimig/paula_audio_channel.v"] \
 [file normalize "${origin_dir}/rtl/minimig/paula_audio_mixer.v"] \
 [file normalize "${origin_dir}/rtl/minimig/paula_audio_sigmadelta.v"] \
 [file normalize "${origin_dir}/rtl/minimig/paula_audio_volume.v"] \
 [file normalize "${origin_dir}/rtl/minimig/paula_floppy.v"] \
 [file normalize "${origin_dir}/rtl/minimig/paula_floppy_fifo.v"] \
 [file normalize "${origin_dir}/rtl/minimig/paula_intcontroller.v"] \
 [file normalize "${origin_dir}/rtl/minimig/paula_uart.v"] \
 [file normalize "${origin_dir}/rtl/audio/audiofilter.vhd"] \
 [file normalize "${origin_dir}/rtl/minimig/paula.v"] \
 [file normalize "${origin_dir}/rtl/minimig/denise_bitplane_shifter.v"] \
 [file normalize "${origin_dir}/rtl/minimig/denise_bitplanes.v"] \
 [file normalize "${origin_dir}/rtl/minimig/denise_collision.v"] \
 [file normalize "${origin_dir}/rtl/minimig/denise_colortable.v"] \
 [file normalize "${origin_dir}/rtl/minimig/denise_colortable_ram_mf.v"] \
 [file normalize "${origin_dir}/rtl/minimig/denise_hamgenerator.v"] \
 [file normalize "${origin_dir}/rtl/minimig/denise_playfields.v"] \
 [file normalize "${origin_dir}/rtl/minimig/denise_spritepriority.v"] \
 [file normalize "${origin_dir}/rtl/minimig/denise_sprites.v"] \
 [file normalize "${origin_dir}/rtl/minimig/denise_sprites_shifter.v"] \
 [file normalize "${origin_dir}/rtl/minimig/denise.v"] \
 [file normalize "${origin_dir}/rtl/minimig/amber.v"] \
 [file normalize "${origin_dir}/rtl/minimig/ciaa.v"] \
 [file normalize "${origin_dir}/rtl/minimig/cia_int.v"] \
 [file normalize "${origin_dir}/rtl/minimig/cia_timera.v"] \
 [file normalize "${origin_dir}/rtl/minimig/cia_timerb.v"] \
 [file normalize "${origin_dir}/rtl/minimig/cia_timerd.v"] \
 [file normalize "${origin_dir}/rtl/minimig/ciab.v"] \
 [file normalize "${origin_dir}/rtl/minimig/gary.v"] \
 [file normalize "${origin_dir}/rtl/minimig/gayle_fifo.v"] \
 [file normalize "${origin_dir}/rtl/minimig/gayle.v"] \
 [file normalize "${origin_dir}/rtl/minimig/minimig_autoconfig_rom.v"] \
 [file normalize "${origin_dir}/rtl/minimig/minimig_autoconfig.v"] \
 [file normalize "${origin_dir}/rtl/chameleonv1/gen_reset.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/rtl/soc/openaars_defines.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj
set_property -name "is_global_include" -value "1" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/ciaa_ps2keyboard_map.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/fpga/openaars/minimig_version.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/clock/amiga_clk.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/clock/amiga_clk_xilinx.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/cart.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/ciaa_ps2keyboard.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/sdram/dpram_inf_generic.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/host/hostcache.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/minimig.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/minimig_bankmapper.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/minimig_m68k_bridge.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/minimig_sram_bridge.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/minimig_syscontrol.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/soc/minimig_virtual_top.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/userio.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/userio_osd.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/userio_osd_spi.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/userio_ps2mouse.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/amiga_keyboard.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/EightThirtyTwo/RTL/eightthirtytwo_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/EightThirtyTwo/RTL/eightthirtytwo_aligner_le.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/EightThirtyTwo/RTL/eightthirtytwo_aligner.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/EightThirtyTwo/RTL/eightthirtytwo_fetchloadstore.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/EightThirtyTwo/RTL/eightthirtytwo_decode.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/EightThirtyTwo/RTL/eightthirtytwo_shifter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/EightThirtyTwo/RTL/eightthirtytwo_alu.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/EightThirtyTwo/RTL/eightthirtytwo_hazard.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/EightThirtyTwo/RTL/eightthirtytwo_debug.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/EightThirtyTwo/RTL/eightthirtytwo_cpu.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/EightThirtyTwo/RTL/debug_virtualjtag.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/EightThirtyTwo/RTL/debug_fifo_altera.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/EightThirtyTwo/RTL/debug_bridge_jtag.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/fw/ctrl_boot_832/OSDBoot_832_ROM.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/host/832_bridge.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/audio/AudioMix.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/tg68k/TG68K_Pack.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/rtg/VideoStream.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/host/cfide.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/soc/TG68K.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/denise_hamgenerator_ram_mf.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "is_enabled" -value "0" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/tg68k/TG68K_ALU.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/tg68k/TG68KdotC_Kernel.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/akiko/akiko.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/akiko/cornerturn.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/soc/minimig_openaars_top.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/openaars/adv7511/signal_generator.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/openaars/adv7511/pal_to_ddr.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/openaars/adv7511/pal_to_hd_upsample.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/openaars/mcp23s17/mcp23s17_input.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/openaars/adv7511/adv_ddr.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/openaars/adv7511/i2c_master.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/openaars/i2s_tx.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/openaars/mcp23s17/spi_master.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/openaars/adv7511/i2c_sender.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/openaars/adv7511/bram_tdp.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/sdram/cpu_cache_new.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/sdram/dpram_256x32.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/sdram/dpram_be_1024x32.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/sdram/sdram_ctrl.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/agnus_audiodma.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/agnus_beamcounter.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/agnus_bitplanedma.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/agnus_blitter.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/agnus_blitter_adrgen.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/agnus_blitter_barrelshifter.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/agnus_blitter_fill.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/agnus_blitter_minterm.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/agnus_copper.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/agnus_diskdma.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/agnus_refresh.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/agnus_spritedma.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/agnus.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/paula_audio.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/paula_audio_channel.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/paula_audio_mixer.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/paula_audio_sigmadelta.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/paula_audio_volume.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/paula_floppy.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/paula_floppy_fifo.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/paula_intcontroller.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/paula_uart.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/audio/audiofilter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/paula.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/denise_bitplane_shifter.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/denise_bitplanes.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/denise_collision.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/denise_colortable.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/denise_colortable_ram_mf.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/denise_hamgenerator.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/denise_playfields.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/denise_spritepriority.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/denise_sprites.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/denise_sprites_shifter.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/denise.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/amber.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/ciaa.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/cia_int.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/cia_timera.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/cia_timerb.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/cia_timerd.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/ciab.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/gary.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/gayle_fifo.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/gayle.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/minimig_autoconfig_rom.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/minimig/minimig_autoconfig.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/chameleonv1/gen_reset.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "generic" -value "MINIMIG_PS2_KEYBOARD MINIMIG_PS2_MOUSE" -objects $obj
set_property -name "top" -value "minimig_openaars_top" -objects $obj
set_property -name "vhdl_generic" -value "MINIMIG_PS2_KEYBOARD MINIMIG_PS2_MOUSE" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/fpga/openaars/aars_v4.0_lite/adv7511_video.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/fpga/openaars/aars_v4.0_lite/adv7511_video.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/fpga/openaars/aars_v4.0_lite/buttons.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/fpga/openaars/aars_v4.0_lite/buttons.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/fpga/openaars/aars_v4.0_lite/floppy.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/fpga/openaars/aars_v4.0_lite/floppy.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/fpga/openaars/aars_v4.0_lite/generic.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/fpga/openaars/aars_v4.0_lite/generic.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/fpga/openaars/aars_v4.0_lite/i2s.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/fpga/openaars/aars_v4.0_lite/i2s.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/fpga/openaars/aars_v4.0_lite/joystick.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/fpga/openaars/aars_v4.0_lite/joystick.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/fpga/openaars/aars_v4.0_lite/leds.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/fpga/openaars/aars_v4.0_lite/leds.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/fpga/openaars/aars_v4.0_lite/pmod.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/fpga/openaars/aars_v4.0_lite/pmod.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/fpga/openaars/aars_v4.0_lite/ps2.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/fpga/openaars/aars_v4.0_lite/ps2.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/fpga/openaars/aars_v4.0_lite/sd_card.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/fpga/openaars/aars_v4.0_lite/sd_card.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/fpga/openaars/aars_v4.0_lite/sdram.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/fpga/openaars/aars_v4.0_lite/sdram.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/fpga/openaars/aars_v4.0_lite/timing.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/fpga/openaars/aars_v4.0_lite/timing.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/fpga/openaars/aars_v4.0_lite/uart.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/fpga/openaars/aars_v4.0_lite/uart.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/fpga/openaars/aars_v4.0_lite/wizard.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/fpga/openaars/aars_v4.0_lite/wizard.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[file normalize "$origin_dir/fpga/openaars/aars_v4.0_lite/wizard.xdc"]" -objects $obj
set_property -name "target_part" -value "xc7a100tfgg676-2" -objects $obj
set_property -name "target_ucf" -value "[file normalize "$origin_dir/fpga/openaars/aars_v4.0_lite/wizard.xdc"]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "top" -value "minimig_openaars_top" -objects $obj
set_property -name "xsim.compile.xvlog.more_options" -value "-d MINIMIG_OPENAARS" -objects $obj

# Create 'ps2mouse' fileset (if not found)
if {[string equal [get_filesets -quiet ps2mouse] ""]} {
  create_fileset -simset ps2mouse
}

# Set 'ps2mouse' fileset object
set obj [get_filesets ps2mouse]
set files [list \
 [file normalize "${origin_dir}/bench/ps2mouse/ps2mouse_ctrl.v"] \
 [file normalize "${origin_dir}/bench/ps2mouse/ps2mouse_tb.v"] \
 [file normalize "${origin_dir}/rtl/minimig/userio_ps2mouse.v"] \
]
add_files -norecurse -fileset $obj $files

# Set 'ps2mouse' fileset file properties for remote files
set file "$origin_dir/bench/ps2mouse/ps2mouse_ctrl.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets ps2mouse] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj
set_property -name "used_in" -value "simulation" -objects $file_obj
set_property -name "used_in_implementation" -value "0" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

set file "$origin_dir/bench/ps2mouse/ps2mouse_tb.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets ps2mouse] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj
set_property -name "used_in" -value "simulation" -objects $file_obj
set_property -name "used_in_implementation" -value "0" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

set file "$origin_dir/rtl/minimig/userio_ps2mouse.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets ps2mouse] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj


# Set 'ps2mouse' fileset file properties for local files
# None

# Set 'ps2mouse' fileset properties
set obj [get_filesets ps2mouse]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "source_set" -value "" -objects $obj
set_property -name "top" -value "ps2mouse_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "xsim.compile.xvlog.more_options" -value "-d MINIMIG_OPENAARS" -objects $obj

# Create 'rom-hostcpu-test' fileset (if not found)
if {[string equal [get_filesets -quiet rom-hostcpu-test] ""]} {
  create_fileset -simset rom-hostcpu-test
}

# Set 'rom-hostcpu-test' fileset object
set obj [get_filesets rom-hostcpu-test]
set files [list \
 [file normalize "${origin_dir}/sim/rom-hostcpu-test/memtest_top_tb.v"] \
 [file normalize "${origin_dir}/sim/rom-hostcpu-test/memtest_orig_top_tb.vhd"] \
 [file normalize "${origin_dir}/fw/ctrl_boot_832/OSDBoot_832_ROM.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Set 'rom-hostcpu-test' fileset file properties for remote files
set file "$origin_dir/sim/rom-hostcpu-test/memtest_top_tb.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets rom-hostcpu-test] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/sim/rom-hostcpu-test/memtest_orig_top_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets rom-hostcpu-test] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/fw/ctrl_boot_832/OSDBoot_832_ROM.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets rom-hostcpu-test] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj


# Set 'rom-hostcpu-test' fileset file properties for local files
# None

# Set 'rom-hostcpu-test' fileset properties
set obj [get_filesets rom-hostcpu-test]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "source_set" -value "" -objects $obj
set_property -name "top" -value "memtest_top_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "xsim.compile.xvlog.more_options" -value "-d MINIMIG_OPENAARS" -objects $obj

# Create 'hostcpu-i2c-bridge' fileset (if not found)
if {[string equal [get_filesets -quiet hostcpu-i2c-bridge] ""]} {
  create_fileset -simset hostcpu-i2c-bridge
}

# Set 'hostcpu-i2c-bridge' fileset object
set obj [get_filesets hostcpu-i2c-bridge]
set files [list \
 [file normalize "${origin_dir}/rtl/host/cfide.vhd"] \
 [file normalize "${origin_dir}/sim/hostcpu-i2c-bridge/i2c_bridge_tb.v"] \
 [file normalize "${origin_dir}/rtl/openaars/adv7511/i2c_master.v"] \
]
add_files -norecurse -fileset $obj $files

# Set 'hostcpu-i2c-bridge' fileset file properties for remote files
set file "$origin_dir/rtl/host/cfide.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets hostcpu-i2c-bridge] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/sim/hostcpu-i2c-bridge/i2c_bridge_tb.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets hostcpu-i2c-bridge] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/rtl/openaars/adv7511/i2c_master.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets hostcpu-i2c-bridge] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj


# Set 'hostcpu-i2c-bridge' fileset file properties for local files
# None

# Set 'hostcpu-i2c-bridge' fileset properties
set obj [get_filesets hostcpu-i2c-bridge]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "source_set" -value "" -objects $obj
set_property -name "top" -value "i2c_bridge_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "xsim.compile.xvlog.more_options" -value "-d MINIMIG_OPENAARS" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/project_1/project_1.srcs/utils_1/imports/synth_1/minimig_openaars_top.dcp"]\
 [file normalize "${origin_dir}/project_1/project_1.srcs/utils_1/imports/impl_1/minimig_openaars_top_routed.dcp"]\
]
set imported_files [import_files -fileset utils_1 $files]

# Set 'utils_1' fileset file properties for remote files
# None

# Set 'utils_1' fileset file properties for local files
set file "synth_1/minimig_openaars_top.dcp"
set file_obj [get_files -of_objects [get_filesets utils_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj
set_property -name "netlist_only" -value "0" -objects $file_obj

set file "impl_1/minimig_openaars_top_routed.dcp"
set file_obj [get_files -of_objects [get_filesets utils_1] [list "*$file"]]
set_property -name "library" -value "work" -objects $file_obj
set_property -name "netlist_only" -value "0" -objects $file_obj


# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a100tfgg676-2 -flow {Vivado Synthesis 2020} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2020" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7a100tfgg676-2" -objects $obj
set_property -name "write_incremental_synth_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a100tfgg676-2 -flow {Vivado Implementation 2020} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2020" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7a100tfgg676-2" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.bin_file" -value "1" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
