#!/usr/bin/env python3
"""Generate the plan-M3 program benches (tb/pipe_asm/*.s of the pipelined tree).

  mk_m3progs.py <pipe_asm dir>

Writes shift_edges.s, bitops.s, muldiv.s, bcd.s, chk.s.  Each logs CCR (or
SR) and the result of every case to a log at $8000 through a6; trap
handlers log the whole format-$2 frame (SR, PC, format/vector, address).
The .exp files come from a reference-core run (mkprog.sh) and are
reviewed by hand; the manual is the authority (PLAN 7).
"""
import sys, os

OUT = sys.argv[1]
LOG = 0x8000

HDR = """v_adr	equ	unexp
v_ill	equ	unexp
v_prv	equ	unexp
v_alin	equ	unexp
v_flin	equ	unexp
v_fmt	equ	unexp
v_trp0	equ	unexp
{extra}	include	"vectors.inc"

	org	$400
start:
	movea.l	#${log:x},a6
"""
TAIL = """	move.l	a6,d0			; the log end, so the range check covers it
halt:
	bra.s	halt
unexp:
	bra.s	unexp
{handlers}
"""
# logs the format-$2 frame: SR, PC, format/vector, address; 12 bytes
TRAPH = """{name}:
	move.w	(sp),(a6)+
	move.l	2(sp),(a6)+
	move.w	6(sp),(a6)+
	move.l	8(sp),(a6)+
	rte
"""


def emit(name, doc, body, nlog, extra="", handlers="", cycles=None):
    end = LOG + ((nlog + 3) & ~3) + 4
    hd = "; %s.s - %s\n" % (name, doc)
    hd += "; Generated by findings/ap040-pipelined/tests/mk_m3progs.py; expect file from the reference.\n"
    if cycles:
        hd += "; diff: --cycles %d\n" % cycles
    hd += "; expect-inimage\n; expect-range: %x %x\n" % (LOG, end)
    src = hd + HDR.format(extra=extra, log=LOG) + "".join(body) + TAIL.format(handlers=handlers)
    open(os.path.join(OUT, name + ".s"), "w").write(src)
    print("%s.s: %d log bytes, %d lines" % (name, nlog, src.count("\n")))


def logcr(reg="d1", sz="l"):
    return "\tmove.w\tccr,(a6)+\n\tmove.%s\t%s,(a6)+\n" % (sz, reg), 2 + {"b": 1, "w": 2, "l": 4}[sz]


# ------------------------------------------------------------ shift edges
def shift_edges():
    body, n = [], 0
    ops = ["asl", "asr", "lsl", "lsr", "rol", "ror", "roxl", "roxr"]
    vals = {"b": [0x81, 0x5A], "w": [0x8001, 0x5AA5], "l": [0x80000001, 0x5AA5C33C]}
    bits = {"b": 8, "w": 16, "l": 32}
    for op in ops:
        for sz in "bwl":
            w = bits[sz]
            for cnt in sorted({0, 1, w - 1, w, w + 1, 63, 64, 65}):
                for v in vals[sz]:
                    for x in (0, 0x10):
                        body.append("\tmove.l\t#$%08x,d1\n\tmove.l\t#%d,d2\n\tmove.w\t#$%02x,ccr\n\t%s.%s\td2,d1\n"
                                    % (0xA5A5A500 & ~((1 << w) - 1) | v if w < 32 else v, cnt, x | 0x0F, op, sz))
                        t, k = logcr(); body.append(t); n += k
        # immediate counts 1-8, long
        for cnt in range(1, 9):
            body.append("\tmove.l\t#$C0000003,d1\n\tmove.w\t#$10,ccr\n\t%s.l\t#%d,d1\n" % (op, cnt))
            t, k = logcr(); body.append(t); n += k
        # memory word (count 1), X in both ways
        for x in (0, 0x10):
            body.append("\tmove.w\t#$8001,(a5)\n\tmove.w\t#$%02x,ccr\n\t%s.w\t(a5)\n" % (x, op))
            t, k = logcr("(a5)", "w"); body.append(t); n += k
    body.insert(0, "\tmovea.l\t#$7F00,a5\n")
    emit("shift_edges", "plan M3 tb_ap040_pipe_shift_edges: ASx LSx ROx ROXx .B/.W/.L, "
         "Dn counts 0/1/size-1/size/size+1/63/64/65 (mod 64), X in set and clear, two values; "
         "#1-8; memory .W.  Count 0: C cleared (ROXx: C = X), X unaffected (PRM 4-22 etc.).",
         body, n, cycles=200000)


# ------------------------------------------------------------ bit ops
def bitops():
    body, n = [], 0
    for op in ["btst", "bchg", "bclr", "bset"]:
        for bn in [0, 5, 31, 32, 37, -1]:
            for v in [0x00000000, 0xFFFFFFFF, 0x80000021]:
                body.append("\tmove.l\t#$%08x,d1\n\tmove.l\t#%d,d2\n\tmove.w\t#$1F,ccr\n\t%s\td2,d1\n"
                            % (v, bn, op))
                t, k = logcr(); body.append(t); n += k
        for bn in [0, 7, 8, 13]:
            for v in [0x00, 0xFF, 0x81]:
                body.append("\tmove.b\t#$%02x,(a5)\n\tmove.l\t#%d,d2\n\tmove.w\t#$00,ccr\n\t%s\td2,(a5)\n"
                            % (v, bn, op))
                t, k = logcr("(a5)", "b"); body.append(t); n += k
                body.append("\tmove.b\t#$%02x,1(a5)\n\tmove.w\t#$1F,ccr\n\t%s\t#%d,1(a5)\n" % (v, op, bn))
                t, k = logcr("1(a5)", "b"); body.append(t); n += k
        for bn in [3, 35]:
            body.append("\tmove.l\t#$0000FFF7,d1\n\tmove.w\t#$04,ccr\n\t%s\t#%d,d1\n" % (op, bn))
            t, k = logcr(); body.append(t); n += k
    # BTST Dn,#imm and BTST Dn,(d16,PC)
    for bn in [0, 3, 7, 8, 12]:
        body.append("\tmove.l\t#%d,d2\n\tmove.w\t#$00,ccr\n\tbtst\td2,#$A5\n\tmove.w\tccr,(a6)+\n" % bn)
        body.append("\tmove.w\t#$1F,ccr\n\tbtst\td2,pcbyte(pc)\n\tmove.w\tccr,(a6)+\n")
        n += 4
    # (An)+ / -(An) byte forms and A7 bytes step 2 not needed here (M1); forwarding:
    body.append("\tmoveq\t#6,d2\n\tbset\td2,d1\n\tmove.l\td1,d3\n\tmove.l\td3,(a6)+\n")
    n += 4
    body.insert(0, "\tmovea.l\t#$7F00,a5\n")
    emit("bitops", "plan M3 tb_ap040_pipe_bitops: BTST BCHG BCLR BSET, Dn bit number mod 32, "
         "memory mod 8, static #n (register mod 32), Z from the bit before, X N V C kept; "
         "BTST Dn,#imm and Dn,(d16,PC).", body, n,
         handlers="pcbyte:\tdc.b\t$5A,0\n", cycles=120000)


# ------------------------------------------------------------ MUL / DIV
def muldiv():
    body, n = [], 0
    w16 = [(0x0000, 0x0000), (0xFFFF, 0xFFFF), (0x7FFF, 0x8000), (0x1234, 0x0003), (0x8000, 0x8000), (0x0001, 0xFFFF)]
    for op in ["mulu", "muls"]:
        for a, b in w16:
            body.append("\tmove.l\t#$A5A5%04x,d1\n\tmove.l\t#$5A5A%04x,d2\n\tmove.w\t#$1F,ccr\n\t%s.w\td2,d1\n"
                        % (a, b, op))
            t, k = logcr(); body.append(t); n += k
    l32 = [(0, 0), (0xFFFFFFFF, 0xFFFFFFFF), (0x7FFFFFFF, 2), (0x00010000, 0x00010000), (0x80000000, 0xFFFFFFFF),
           (0x12345678, 0x9ABCDEF0), (3, 5)]
    for op in ["mulu", "muls"]:
        for a, b in l32:
            body.append("\tmove.l\t#$%08x,d1\n\tmove.l\t#$%08x,d2\n\tmove.w\t#$1F,ccr\n\t%s.l\td2,d1\n" % (a, b, op))
            t, k = logcr(); body.append(t); n += k
            body.append("\tmove.l\t#$%08x,d1\n\tmove.l\t#$%08x,d2\n\tmoveq\t#-1,d3\n\tmove.w\t#$00,ccr\n\t%s.l\td2,d3:d1\n"
                        % (a, b, op))
            t, k = logcr(); body.append(t); n += k
            t, k = logcr("d3"); body.append(t); n += k
            # Dh == Dl: the 68040 keeps the low half (reference S_MDL..., t_integer "MULx.L with Dh == Dl")
            body.append("\tmove.l\t#$%08x,d1\n\tmove.l\t#$%08x,d2\n\t%s.l\td2,d1:d1\n" % (a, b, op))
            t, k = logcr(); body.append(t); n += k
    # divide .W
    dw = [(0x00010000, 0x0002), (0xFFFFFFFF, 0x0001), (0x7FFFFFFF, 0x7FFF), (0x00000007, 0xFFFE), (0x80000000, 0xFFFF),
          (0x0000FFFF, 0x0100), (0xFFFF8000, 0xFFFF)]
    for op in ["divu", "divs"]:
        for a, b in dw:
            body.append("\tmove.l\t#$%08x,d1\n\tmove.l\t#$0000%04x,d2\n\tmove.w\t#$1F,ccr\n\t%s.w\td2,d1\n" % (a, b, op))
            t, k = logcr(); body.append(t); n += k
    # divide .L 32/32, with remainder register, and 64/32
    dl = [(100, 7), (0xFFFFFFFF, 1), (0x80000000, 0xFFFFFFFF), (0x7FFFFFFF, 0x10000), (5, 0x80000000), (0xFFFFFFF9, 2)]
    for op in ["divu", "divs"]:
        for a, b in dl:
            body.append("\tmove.l\t#$%08x,d1\n\tmove.l\t#$%08x,d2\n\tmove.w\t#$10,ccr\n\t%s.l\td2,d1\n" % (a, b, op))
            t, k = logcr(); body.append(t); n += k
            body.append("\tmove.l\t#$%08x,d1\n\tmove.l\t#$%08x,d2\n\tmoveq\t#-1,d3\n\tmove.w\t#$10,ccr\n\t%sl.l\td2,d3:d1\n"
                        % (a, b, op))
            t, k = logcr(); body.append(t); n += k
            t, k = logcr("d3"); body.append(t); n += k
        for hi, lo, b in [(0, 100, 7), (1, 0, 2), (0x7FFFFFFF, 0, 1), (0xFFFFFFFF, 0xFFFFFFF0, 3), (0x00000003, 0x00000000, 4)]:
            body.append("\tmove.l\t#$%08x,d1\n\tmove.l\t#$%08x,d3\n\tmove.l\t#$%08x,d2\n\tmove.w\t#$10,ccr\n\t%s.l\td2,d3:d1\n"
                        % (lo, hi, b, op))
            t, k = logcr(); body.append(t); n += k
            t, k = logcr("d3"); body.append(t); n += k
    # divide by zero: vector 5, format $2, PC = the next instruction, address = the DIV
    for form in ["divu.w\td2,d1", "divs.w\td2,d1", "divu.l\td2,d1", "divs.l\td2,d3:d1", "divul.l\td2,d3:d1",
                 "divu.w\t(a5),d1", "divs.l\t#0,d1"]:
        body.append("\tmove.l\t#$12345678,d1\n\tmoveq\t#0,d2\n\tmove.l\t#$0000FFFF,d3\n\tclr.l\t(a5)\n"
                    "\tmove.w\t#$0F,ccr\n\t%s\n\tnop\n" % form)
        n += 12
        t, k = logcr(); body.append(t); n += k
        t, k = logcr("d3"); body.append(t); n += k
    # the result used at once, and a multiply behind a divide (EX busy)
    body.append("\tmove.l\t#1000,d1\n\tmoveq\t#7,d2\n\tdivu.w\td2,d1\n\tmulu.w\td1,d1\n\tadd.l\td1,d1\n\tmove.l\td1,(a6)+\n")
    n += 4
    body.insert(0, "\tmovea.l\t#$7F00,a5\n")
    emit("muldiv", "plan M3 tb_ap040_pipe_muldiv: MULU/MULS .W, .L 32 and 64-bit (Dh:Dl, Dh == Dl), "
         "DIVU/DIVS .W (overflow: V, destination kept), .L 32/32, DIVxL 32/32 with Dr, 64/32 (overflow), "
         "divide by zero: vector 5, format $2, stacked PC = the next instruction (M68040UM 8.2.3 p. 8-8).",
         body, n, extra="v_divz\tequ\ttrap_h\n", handlers=TRAPH.format(name="trap_h"), cycles=200000)


# ------------------------------------------------------------ BCD
def bcd():
    body, n = [], 0
    pairs = [(0x00, 0x00), (0x99, 0x01), (0x45, 0x55), (0x09, 0x09), (0x50, 0x49), (0x00, 0x01), (0x1F, 0x0A),
             (0xFA, 0x06), (0x99, 0x99), (0x80, 0x19)]
    for op in ["abcd", "sbcd"]:
        for a, b in pairs:
            for x in (0x00, 0x10):
                for z in (0x00, 0x04):
                    body.append("\tmove.l\t#$FFFFFF%02x,d1\n\tmove.l\t#$000000%02x,d2\n\tmove.w\t#$%02x,ccr\n\t%s\td2,d1\n"
                                % (a, b, x | z, op))
                    t, k = logcr(); body.append(t); n += k
        # memory -(Ay),-(Ax), a two-byte chain
        body.append("\tlea\t2(a5),a1\n\tlea\t4(a5),a2\n\tmove.w\t#$1999,(a5)\n\tmove.w\t#$0901,2(a5)\n"
                    "\tmove.w\t#$04,ccr\n\t%s\t-(a2),-(a1)\n\t%s\t-(a2),-(a1)\n" % (op, op))
        t, k = logcr("(a5)"); body.append(t); n += k
        t, k = logcr("a1"); body.append(t); n += k
    for v in [0x00, 0x01, 0x99, 0x50, 0x0F, 0xA0]:
        for x in (0x00, 0x10):
            for z in (0x00, 0x04):
                body.append("\tmove.l\t#$123456%02x,d1\n\tmove.w\t#$%02x,ccr\n\tnbcd\td1\n" % (v, x | z))
                t, k = logcr(); body.append(t); n += k
    body.append("\tmove.b\t#$42,(a5)\n\tmove.w\t#$04,ccr\n\tnbcd\t(a5)\n")
    t, k = logcr("(a5)", "b"); body.append(t); n += k
    body.insert(0, "\tmovea.l\t#$7F00,a5\n")
    emit("bcd", "plan M3 tb_ap040_pipe_bcd: ABCD SBCD NBCD, register and -(An) memory forms, "
         "X in both ways, Z sticky (cleared if nonzero, else unchanged), invalid digits.",
         body, n, cycles=120000)


# ------------------------------------------------------------ CHK / CHK2 / TRAPcc
def chk():
    body, n = [], 0
    # CHK.W / CHK.L: in bounds, above, negative, at the bounds
    for sz, bound, vals in [("w", 0x0100, [0, 0x100, 0x101, 0xFFFF, 0x7FFF, 0x80]),
                            ("l", 0x00010000, [0, 0x10000, 0x10001, 0xFFFFFFFF, 0x80000000, 5])]:
        for v in vals:
            body.append("\tmove.l\t#$%08x,d1\n\tmove.l\t#$%08x,d2\n\tmove.w\t#$1F,ccr\n\tchk.%s\td2,d1\n\tnop\n"
                        % (v, bound, sz))
            t, k = logcr(); body.append(t); n += k + 12   # a trap logs a frame too (reserved)
    # negative bound
    body.append("\tmove.l\t#$FFFF,d2\n\tmoveq\t#0,d1\n\tmove.w\t#$00,ccr\n\tchk.w\td2,d1\n\tnop\n")
    t, k = logcr(); body.append(t); n += k + 12
    # CHK2 / CMP2: bounds in memory; signed lb<=ub, unsigned-style lb>ub, An forms
    bounds = [("b", 0x10, 0x20, [0x0F, 0x10, 0x15, 0x20, 0x21, 0x90]),
              ("b", 0xF0, 0x10, [0xEF, 0xF0, 0x00, 0x10, 0x11, 0x80]),
              ("b", 0x20, 0x10, [0x05, 0x10, 0x15, 0x20, 0x25, 0x90]),   # lb > ub: the wrapped range
              ("w", 0x8000, 0x7FFF, [0x0000, 0x8000, 0x7FFF]),
              ("w", 0x0100, 0x0200, [0x00FF, 0x0100, 0x0180, 0x0200, 0x0201]),
              ("l", 0x00000010, 0x00000100, [0x0F, 0x10, 0x100, 0x101, 0xFFFFFFFF])]
    for sz, lb, ub, vals in bounds:
        szb = {"b": 1, "w": 2, "l": 4}[sz]
        body.append("\tmove.%s\t#$%x,(a5)\n\tmove.%s\t#$%x,%d(a5)\n" % (sz, lb, sz, ub, szb))
        for v in vals:
            for op in ["cmp2", "chk2"]:
                body.append("\tmove.l\t#$A5A5A5%02x,d1\n\tmove.l\t#$%08x,d1\n" % (0, v) if sz == "l" else
                            "\tmove.l\t#$A5A5A5A5,d1\n\tmove.%s\t#$%x,d1\n" % (sz, v))
                body.append("\tmove.w\t#$1F,ccr\n\t%s.%s\t(a5),d1\n\tnop\n" % (op, sz))
                t, k = logcr(); body.append(t); n += k + 12
        if sz == "w":   # An: the bounds are sign-extended, compared as longs
            for v in [0xFFFF8000, 0x00007FFF, 0x00008000]:
                body.append("\tmovea.l\t#$%08x,a1\n\tmove.w\t#$1F,ccr\n\tchk2.w\t(a5),a1\n\tnop\n" % v)
                n += 2 + 12
                body.append("\tmove.w\tccr,(a6)+\n")
    # TRAPV and TRAPcc: all three forms, taken and not
    for ccr in (0x00, 0x02, 0x04, 0x0B):
        body.append("\tmove.w\t#$%02x,ccr\n\ttrapv\n\tnop\n\tmove.w\tccr,(a6)+\n" % ccr)
        n += 2 + 12
        for cc in ["t", "f", "eq", "ne", "vs", "mi", "hi"]:
            body.append("\tmove.w\t#$%02x,ccr\n\ttrap%s\n\tnop\n\tmove.w\tccr,(a6)+\n" % (ccr, cc))
            body.append("\tmove.w\t#$%02x,ccr\n\ttrap%s.w\t#$1234\n\tnop\n\tmove.w\tccr,(a6)+\n" % (ccr, cc))
            body.append("\tmove.w\t#$%02x,ccr\n\ttrap%s.l\t#$12345678\n\tnop\n\tmove.w\tccr,(a6)+\n" % (ccr, cc))
            n += 3 * (2 + 12)
    # a CHK whose operand was loaded by the instruction before (forwarding)
    body.append("\tmove.l\t#$200,d1\n\tmove.w\t#$100,d2\n\tchk.w\td2,d1\n\tnop\n\tmove.w\tccr,(a6)+\n")
    n += 2 + 12
    body.insert(0, "\tmovea.l\t#$7F00,a5\n")
    emit("chk", "plan M3 tb_ap040_pipe_chk: CHK.W/.L (N tracks the sign, Z C V undefined -> as the "
         "reference), CHK2/CMP2 .B/.W/.L signed and wrapped bounds, An with sign-extended bounds, "
         "TRAPV, TRAPcc / TRAPcc.W / TRAPcc.L; vectors 6 and 7, format $2, stacked PC = the next "
         "instruction, address = the trapping one (M68040UM 8.2.3 p. 8-8).", body, n,
         extra="v_chk\tequ\ttrap_h\nv_trapv\tequ\ttrap_h\n", handlers=TRAPH.format(name="trap_h"), cycles=200000)


shift_edges(); bitops(); muldiv(); bcd(); chk()
