#!/usr/bin/env python3
"""Build the pipelined core's variant of the reference's t_mmu.s (plan M7).

  mk_tmmu.py <lib/AP68040/tb/asm/t_mmu.s> <milestone> > asm/diff_tmmu_<m>.s

The reference program is used unchanged except for the patches below.
Every patch asserts its anchor text, so the variant follows the file if
it changes and fails loudly if a patch no longer applies.

1. h_aerr, write faults (PLAN D13).  The reference core restarts every
   faulted write, so its h_aerr expects WB3S clear, WB3A = FA and WB3D =
   the data, and returns without doing the write.  The pipelined core
   follows M68040UM 8.4.6.3 (p. 8-26..8-29) instead: a write that faults
   on an instruction's last micro-op is reported pending in WB1 (WB1S
   valid, WB1A = FA, WB1D = the data) and the stacked PC is the next
   instruction, so the handler has to perform the write -- which is what
   NetBSD's trap.c writeback() does for WB1.  The patched handler
     - captures WB1D as "the write data" (last_wb3d) when WB1S is valid,
     - skips the WB3A = FA check when WB1S is valid,
     - performs the WB1 write (byte/word/long/line) after repairing the
       mapping, as NetBSD does, whether or not wb_complete is set.
   Every numbered check of the program stays as it is.
2. The interleave sweeps (161-167) need interrupts (M9): skipped with a
   branch, as the program itself does on a bench without IPL injection.
3. The ending: STOP (M9) is replaced by a branch to self after $600D.
4. h_aerr, MOVEM faults (PLAN D15): the EA = FA check is skipped when SSW CM
   is set (the manual stacks the MOVEM's calculated EA there).
"""
import sys

src, ms = sys.argv[1], sys.argv[2]
s = open(src).read()

def patch(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor %r found %d times" % (old, n)
    s = s.replace(old, new)

# 1. h_aerr: the manual's WB1 for a faulted final write
patch("""	move.l	$28(sp),(last_wb3d).l
""", """	move.l	$28(sp),(last_wb3d).l
	move.w	$1E(sp),d0	; (pipelined, D13) WB1S valid: WB1D is the write
	btst	#7,d0
	beq.s	hm_nwb1
	move.l	$38(sp),(last_wb3d).l
hm_nwb1:
""")
patch("""	move.w	$18(sp),d0
	btst	#8,d0		; write fault: WB3A must mirror the FA
""", """	move.w	$1E(sp),d0	; (pipelined, D13) the write is pending in WB1:
	btst	#7,d0		; WB1A mirrors the FA, WB3 is empty
	bne.s	haerr_wbok
	move.w	$18(sp),d0
	btst	#8,d0		; write fault: WB3A must mirror the FA
""")
patch("""	pflusha
	; NetBSD order: repair the mapping FIRST, then complete writebacks
""", """	pflusha
	; (pipelined, D13) NetBSD trap.c writeback(): a valid WB1 is performed
	; by the handler -- the 68040 does not re-run the faulted write
	move.w	$1E(sp),d0
	btst	#7,d0
	beq.s	hm_wb1done
	movea.l	$34(sp),a0	; WB1A
	and.w	#$0060,d0
	cmp.w	#$0020,d0
	beq.s	hm_wb1b
	cmp.w	#$0040,d0
	beq.s	hm_wb1w
	cmp.w	#$0060,d0
	beq.s	hm_wb1l
	move.l	$38(sp),(a0)	; long
	bra.s	hm_wb1done
hm_wb1b:
	move.b	$3B(sp),(a0)
	bra.s	hm_wb1done
hm_wb1w:
	move.w	$3A(sp),(a0)
	bra.s	hm_wb1done
hm_wb1l:
	move.l	a0,d0		; MOVE16 line: PD0-PD3 to the aligned line
	and.l	#$FFFFFFF0,d0
	movea.l	d0,a0
	move.l	$38(sp),(a0)+
	move.l	$3C(sp),(a0)+
	move.l	$40(sp),(a0)+
	move.l	$44(sp),(a0)+
hm_wb1done:
	; NetBSD order: repair the mapping FIRST, then complete writebacks
""")

# 1b. h_aerr, MOVEM faults (PLAN D15): M68040UM 8.4.6.2 (p. 8-25) -- and
# WinUAE's 68040 MMU mode, cpummu.cpp mmu040_movem -- set SSW CM and stack
# the MOVEM's calculated EA, not the fault address; lib/AP68040 never sets
# CM, and h_aerr checks EA = FA.  The patched handler skips that one check
# when CM is set (FA is still checked).
patch("""	move.l	$14(sp),d0	; EA field: WinUAE stacks the fault address here
""", """	move.w	$18(sp),d0	; (pipelined, D15) CM: the EA field is the MOVEM's
	btst	#12,d0		; calculated EA, not the fault address
	bne	haerr_eaok
	move.l	$14(sp),d0	; EA field: WinUAE stacks the fault address here
""")

# 2. no interrupts before M9
if ms in ("m7", "m8"):
    patch("""	btst	#0,d0		; injection; benches without it advertise 0
	beq	imix_done""", """	btst	#0,d0		; injection; benches without it advertise 0
	bra	imix_done	; (pipelined: interrupts are plan M9)""")

# 3. no STOP before M9
if ms in ("m7", "m8"):
    patch("""	move.w	#$600D,(DONEREG).l
	stop	#$2700
""", """	move.w	#$600D,(DONEREG).l
halt_ok:
	bra.s	halt_ok		; (pipelined: STOP is plan M9)
""")

print("; Generated by mk_tmmu.py %s from %s -- do not edit" % (ms, src))
print(s, end="")
