#!/usr/bin/env python3
"""Build a milestone extract of the reference's t_integer.s.

  mk_tint.py <lib/AP68040/tb/asm/t_integer.s> <milestone> > asm/diff_tint_<m>.s

The reference program is used UNCHANGED except that sections testing
instructions of later milestones are left out (their numbered checks
simply do not run), and the ending (CINVA, STOP: M8/M9) is replaced by the
$600D write and a branch-to-self.  Section boundaries are the reference's
own ';-----' banner lines, so the extract follows the file if it changes.
"""
import re, sys

src, ms = sys.argv[1], sys.argv[2]
lines = open(src).read().split("\n")
# sections by banner
secs = []   # (title, start, end)
idx = [i for i, l in enumerate(lines) if re.match(r";-{10,}", l)]
for k, i in enumerate(idx):
    title = lines[i].lstrip(";-").strip()
    secs.append((title, i, idx[k + 1] if k + 1 < len(idx) else len(lines)))
KEEP = {
    "m2": {"run cache-hot (P1)", "moveq", "add/sub flags", "addx/subx", "logic", "neg",
           "ext/swap/exg", "EA modes", "adda/cmpa", "addq/subq to An", "control flow",
           "ccr moves", "tst"},
    "m3": {"run cache-hot (P1)", "moveq", "add/sub flags", "addx/subx", "logic", "neg",
           "shifts", "bit ops", "word mul/div", "long mul/div", "BCD",
           "ext/swap/exg", "EA modes", "adda/cmpa", "addq/subq to An", "control flow",
           "pack/unpk", "ccr moves", "tst", "bitfields", "CAS", "BTST Dn,#imm and CMP2", "CAS2", "BCD with",
           "CHK flags", "DIVS.L 32-bit overflow", "MULx.L with Dh == Dl",
           "shift/rotate count edges"},
    "m4": None,   # the whole program (M4 exit: full t_integer.s parity)
    # t_exceptions.s, the sections plan M4 names plus the M3 trap sections
    # (trace, interrupts, FSAVE, PTEST/PFLUSH, bus/address errors, M bit are later)
    "exc_m4": {"TRAP #0", "illegal / BKPT", "A/F-line", "CHK", "divide by zero", "TRAPV / TRAPcc",
               "MOVEC matrix", "MOVE USP", "MOVES", "user mode round trip",
               "immediate group: destination must be data alterable"},
    "exc_m6": {"TRAP #0", "illegal / BKPT", "A/F-line", "CHK", "divide by zero", "TRAPV / TRAPcc",
               "MOVEC matrix", "MOVE USP", "MOVES", "user mode round trip", "format error",
               "address error", "physical bus error",
               "immediate group: destination must be data alterable"},
    # plan M9 subset (pulled forward for gate 1, Paul Q8 (a)): interrupts
    # (autovectors, masking, the held level, NMI edge, STOP wake) and the
    # level-sensitive IPL section; trace, M-bit throwaway frames stay M9
    "exc_m9s": {"TRAP #0", "illegal / BKPT", "A/F-line", "CHK", "divide by zero", "TRAPV / TRAPcc",
               "MOVEC matrix", "MOVE USP", "MOVES", "user mode round trip", "format error",
               "address error", "physical bus error",
               "immediate group: destination must be data alterable",
               "interrupts", "level-sensitive IPL: the NetBSD ports shape"},
}[ms]
DROP_BLOCKS = {"m2": [r"^\s*; tas$"], "m3": [], "m4": [], "exc_m4": [], "exc_m6": [r"^\s*; FRESTORE must reject", r"^\s*; A full MC68040 does not recognize"], "exc_m9s": [r"^\s*; FRESTORE must reject", r"^\s*; A full MC68040 does not recognize"]}[ms]   # (FRESTORE and the format-$4 test depend on the FPU: M10)   # blocks (to the next blank line) inside kept sections
out = lines[:idx[0]]                        # header: macros, vectors, org, start
for title, a, b in secs:
    if title == "all done":
        out += [lines[a], "\tmove.w\t#$600D,(DONEREG).l", "halt:", "\tbra.s\thalt", ""]
        continue
    if title in ("helpers", "handlers", "wait loops"):
        out += lines[a:b]
        continue
    if KEEP is not None and title not in KEEP:
        out += ["; (section '%s' left out of the %s extract)" % (title, ms), ""]
        continue
    body = lines[a:b]
    res, skip = [], False
    for l in body:
        if any(re.match(p, l) for p in DROP_BLOCKS):
            skip = True
            res.append("; (block '%s' left out of the %s extract)" % (l.strip(), ms))
            continue
        if skip and l.strip() == "":
            skip = False
        if not skip:
            res.append(l)
    out += res
print("; diff: --cycles 60000")
print("; expect-mem: m16 f100 m16 f102")
print("; Generated by mk_tint.py %s from %s -- do not edit" % (ms, src))
print("\n".join(out))
