#!/usr/bin/env python3
"""Build the pipelined core's variant of apolkosnik/AP68040's t_movem_restart.s.

  mk_tmovem.py <AP68040-reference/tb/asm/t_movem_restart.s> <milestone> > t_movem_restart_<m>.s

Unchanged except, before M9 (no interrupts, no STOP): case 7 (a pending
level-2 interrupt taken after the CM restart) is skipped, and the final
STOP becomes a branch to self.  Anchors are asserted.
"""
import sys
src, ms = sys.argv[1], sys.argv[2]
s = open(src).read()
def patch(old, new):
    global s
    assert s.count(old) == 1, "anchor %r found %d times" % (old, s.count(old))
    s = s.replace(old, new)
if ms in ("m7", "m8"):
    patch("""        addq.w  #1,(which).l
        cmpi.w  #9,(which).l""", """        addq.w  #1,(which).l
        cmpi.w  #7,(which).l          ; (pipelined: case 7 needs interrupts, plan M9)
        bne.s   pipe_no7
        addq.w  #1,(which).l
pipe_no7:
        cmpi.w  #9,(which).l""")
    patch("""        move.w  #$600D,(DONEREG).l
        stop    #$2700""", """        move.w  #$600D,(DONEREG).l
pipe_halt:
        bra.s   pipe_halt             ; (pipelined: STOP is plan M9)""")
print("; Generated by mk_tmovem.py %s from %s -- do not edit" % (ms, src))
print(s, end="")
