#!/usr/bin/env python3
"""Make a tb_ap040_pipe_prog.v expect file from a REFERENCE run.

  mkexp.py <prog.s> <ref_trace.txt> <prog.hex> > prog.exp

The halt PC is the label `halt` (found in the vasm listing next to the
.s, or given with --halt).  Registers come from the reference's last
state line; memory from the program image overlaid with the reference's W
stream.  Which memory to check is named in the source with lines
    ; expect-mem: m32 1200 m16 1206 m8 120b ...
and extra registers to skip with
    ; expect-skip: d7 a6
The output is reviewed by hand before it is committed: the reference is
the parity target, the manual is the authority (PLAN.md section 7).
"""
import re, sys, argparse

COLS = "pc sr d0 d1 d2 d3 d4 d5 d6 d7 a0 a1 a2 a3 a4 a5 a6 a7".split()

ap = argparse.ArgumentParser()
ap.add_argument("src"); ap.add_argument("ref"); ap.add_argument("hex")
ap.add_argument("--halt", type=lambda s: int(s, 16))
a = ap.parse_args()

src = open(a.src).read()
mem = {}
words = [int(l, 16) for l in open(a.hex) if l.strip()]
for i, w in enumerate(words):
    mem[2 * i] = w >> 8; mem[2 * i + 1] = w & 0xFF
last = None
for ln in open(a.ref):
    f = ln.split()
    if not f or f[0].startswith("#"):
        continue
    if f[0] == "W":
        addr, size, data = int(f[1], 16), int(f[2]), int(f[3], 16)
        for k in range(size):
            mem[(addr + k) & 0xFFFF] = (data >> (8 * (size - 1 - k))) & 0xFF
        continue
    if f[0] == "X":
        continue
    last = dict(zip(COLS, f))
halt = a.halt
if halt is None:
    sys.exit("give --halt <pc>")
skip = set()
for m in re.finditer(r";\s*expect-skip:(.*)", src):
    skip |= set(m.group(1).split())
print(f"halt {halt:08x}")
print(f"# generated by mkexp.py from the reference run, then reviewed")
for c in COLS[2:]:
    if c in skip or c == "a7":
        continue
    print(f"{c} {last[c]}")
if "sr" not in skip:
    print(f"sr {int(last['sr'], 16):08x}")
if "a7" not in skip:
    sr = int(last["sr"], 16)
    print(f"{'isp' if sr & 0x2000 and not sr & 0x1000 else 'msp' if sr & 0x2000 else 'usp'} {last['a7']}")
for m in re.finditer(r";\s*expect-mem:(.*)", src):
    t = m.group(1).split()
    for kind, addr in zip(t[0::2], t[1::2]):
        ad = int(addr, 16); n = {"m8": 1, "m16": 2, "m32": 4}[kind]
        v = 0
        for k in range(n):
            v = (v << 8) | mem.get((ad + k) & 0xFFFF, 0x4E if (ad + k) % 2 == 0 else 0x71)
        print(f"{kind} {ad:08x} {v:0{2*n}x}")
for m in re.finditer(r";\s*expect-range:\s*([0-9a-fA-F]+)\s+([0-9a-fA-F]+)", src):
    for ad in range(int(m.group(1), 16), int(m.group(2), 16), 4):
        v = 0
        for k in range(4):
            v = (v << 8) | mem.get((ad + k) & 0xFFFF, 0x4E if (ad + k) % 2 == 0 else 0x71)
        print(f"m32 {ad:08x} {v:08x}")
m = re.search(r";\s*expect-rbcount:\s*(\d+)", src)
if m:
    print(f"rbcount {m.group(1)}")
for m in re.finditer(r";\s*expect-rb:([0-9a-fA-F ]*)", src):
    for x in m.group(1).split():
        print(f"rb {int(x, 16):08x}")
for m in re.finditer(r";\s*expect-readonce:([0-9a-fA-F ]*)", src):
    for x in m.group(1).split():
        print(f"readonce {int(x, 16):08x}")
for m in re.finditer(r";\s*expect-fc:(.*)", src):
    t = m.group(1).split()
    for ad, fc in zip(t[0::2], t[1::2]):
        print(f"fc {int(ad, 16):08x} {int(fc)}")
for m in re.finditer(r";\s*expect-syncpc:\s*(\w+)", src):
    print(f"syncpc {int(m.group(1), 16):08x}")
for m in re.finditer(r";\s*expect-berr:(.*)", src):
    t = m.group(1).split()
    for ad, k in zip(t[0::2], t[1::2]):
        print(f"berr {int(ad, 16):08x} {k}")
if re.search(r";\s*expect-halted", src):
    print("halted")
if re.search(r";\s*expect-inimage", src):
    print("inimage")
for m in re.finditer(r";\s*expect-noread:(.*)", src):
    for addr in m.group(1).split():
        print(f"noread {int(addr, 16):08x}")
