; diff: --cycles 60000
; expect-mem: m16 f100 m16 f102
; Generated by mk_tint.py exc_m4 from ../../../lib/AP68040/tb/asm/t_exceptions.s -- do not edit
; AP040 milestone C exception, interrupt and control register self test
; assembled with vasmm68k_mot -Fbin -m68040
;
; testbench protocol:
;   word write to $F100 = failing test number
;   word write to $F102 = $BAD0 on failure, $600D when all tests passed
;   word write to $F110 = request interrupt level (0 releases)
;   byte write to $F120 must carry FC=1 (MOVES with DFC=1 check in the TB)
;
; frame layout under test (MC68040):
;   format $0: SR@0, PC@2, fmt/vec@6            (8 bytes)
;   format $1: same, throwaway                  (8 bytes)
;   format $2: + address@8                      (12 bytes)

FAILREG	equ	$F100
DONEREG	equ	$F102
IPLREG	equ	$F110
IPLPULSE	equ	$F14C	; raise IPL, then withdraw it N cycles later
IPLDLY	equ	$F148	; raise IPL N cycles from now
IPLSTEP	equ	$F150	; raise IPL, then DOWNGRADE it N cycles later
FBERRCTL equ	$F154	; one-shot bus error on a FETCH at the written address
FCREG	equ	$F120
BERRCTL equ	$F142
IRQEXCCTL equ	$F144
IPLCAP	equ	$F160	; bench capability word: bit 0 = coarse IPL delivery
			; (IPLREG, IPLDLY arriving eventually), bit 1 = cycle-
			; fine injectors (IPLDLY exact, IPLPULSE, IPLSTEP,
			; IRQEXCCTL), bit 2 = bus-error injection (BERRCTL,
			; FBERRCTL), bit 3 = the cache_allow window models
			; production (cache_allow_all=0), bit 4 = the real
			; fastchip/rtg block is instantiated.  Gated tests are
			; bypassed, never faked.

hfa		equ	$3674	; fault address seen by h_buserr
hfpc		equ	$3678	; and its stacked PC
hid		equ	$3670	; which handler called hfail (X2.3a diagnostic)
cnt_trap0	equ	$3600
cnt_ill		equ	$3602
cnt_aline	equ	$3604
cnt_fline	equ	$3606
cnt_chk		equ	$3608
cnt_divz	equ	$360A
cnt_trapv	equ	$360C
cnt_trapcc	equ	$360E
cnt_int2	equ	$3610
cnt_int5	equ	$3612
cnt_nmi		equ	$3614
cnt_mflag	equ	$3616
cnt_priv	equ	$3618
cnt_trapu	equ	$361A
cnt_fmt		equ	$361C
cnt_addr	equ	$361E
cnt_trace	equ	$3620
cnt_buserr	equ	$3622
cnt_int3	equ	$3624
cnt_fberr	equ	$3626
resume		equ	$3630
exp_addr	equ	$3634
exp_pc		equ	$3638
addr_sflag	equ	$363C
irq_early	equ	$363E
irq_guard	equ	$3640
buserr_fc	equ	$3642
fberr_fa	equ	$3654
irq_exc	equ	$3644
trap_guard	equ	$3646
exp_sr		equ	$3648
exp_srv		equ	$364A
tw_sr		equ	$364C
got_fsp		equ	$3650
irq_guard2	equ	$3652
int2_pc		equ	$3658	; level-2 frame PC captured by h_int2
trace_pc	equ	$365C	; first trace frame PC since the last clear
order_hit	equ	$3660	; trace-vs-IRQ order test saw a same-boundary hit
hold2		equ	$3664	; h_int2 leaves the line ASSERTED for N entries
kick5		equ	$3666	; h_int2 raises level 5 mid-handler once
nest52		equ	$3668	; h_int5 hands the line back to level 2 once

failt	macro
	move.w	#\1,d7
	bra	fail_all
	endm

chkl	macro
	cmp.l	#\2,\1
	beq.s	ok\@
	failt	\3
ok\@:
	endm

chkccr	macro
	move.w	ccr,d6
	andi.w	#$1F,d6
	cmp.w	#\1,d6
	beq.s	ok\@
	failt	\2
ok\@:
	endm

chkcnt	macro			; \1 = counter address, \2 = expected, \3 = test
	move.w	(\1).l,d6
	cmp.w	#\2,d6
	beq.s	ok\@
	failt	\3
ok\@:
	endm

	org	0
	dc.l	$3400		; ISP
	dc.l	start
	dc.l	h_buserr	; 2 bus error
	dc.l	h_addr		; 3 address error
	dc.l	h_ill		; 4 illegal
	dc.l	h_divz		; 5 divide by zero
	dc.l	h_chk		; 6 CHK
	dc.l	h_trapv		; 7 TRAPV/TRAPcc
	dc.l	h_priv		; 8 privilege violation
	dc.l	h_trace		; 9 trace
	dc.l	h_aline		; 10 A-line
	dc.l	h_fline		; 11 F-line
	dc.l	unexp,unexp	; 12,13
	dc.l	h_fmt		; 14 format error
	dc.l	unexp		; 15
	rept	8
	dc.l	unexp		; 16-23
	endr
	dc.l	unexp,unexp	; 24 spurious, 25 level 1
	dc.l	h_int2		; 26 level 2 autovector
	dc.l	h_int3		; 27 level 3 autovector
	dc.l	unexp		; 28
	dc.l	h_int5		; 29 level 5 autovector
	dc.l	unexp		; 30
	dc.l	h_nmi		; 31 level 7 autovector
	dc.l	h_trap0		; 32 TRAP #0
	dc.l	h_trap1		; 33 TRAP #1
	rept	14
	dc.l	unexp		; 34-47
	endr
	rept	208
	dc.l	unexp		; 48-255
	endr

	org	$400
start:
	lea	(cnt_trap0).l,a0
	moveq	#17,d0
clrloop:
	clr.w	(a0)+
	dbra	d0,clrloop

;----------------------------------------------------------------- TRAP #0
	trap	#0
	chkcnt	cnt_trap0,1,1

;----------------------------------------------------------------- illegal / BKPT
	dc.w	$4AFC		; ILLEGAL
	chkcnt	cnt_ill,1,2
	dc.w	$4848		; BKPT #0: illegal on this implementation
	chkcnt	cnt_ill,2,3

;----------------------------------------------------------------- A/F-line
	dc.w	$A123
	chkcnt	cnt_aline,1,4
	dc.w	$F0FF		; 030 PMMU opcode: F-line on 040
	chkcnt	cnt_fline,1,5

; (section 'FSAVE/FRESTORE' left out of the exc_m4 extract)

;----------------------------------------------------------------- CHK
	move.l	#5,d0
	chk.w	#3,d0		; out of bounds high
	chkcnt	cnt_chk,1,6
	move.l	#-1,d0
	chk.w	#100,d0		; negative
	chkcnt	cnt_chk,2,7
	move.l	#50,d0
	chk.w	#100,d0		; in bounds: no trap
	chkcnt	cnt_chk,2,8
	move.w	#10,($3520).l	; CHK2 bounds pair {10, 20}
	move.w	#20,($3522).l
	moveq	#15,d0
	chk2.w	($3520).l,d0	; inside: no trap
	chkcnt	cnt_chk,2,55
	moveq	#30,d0
	chk2.w	($3520).l,d0	; outside: vector 6, format $2
	chkcnt	cnt_chk,3,56

;----------------------------------------------------------------- divide by zero
	move.l	#7,d0
	divu.w	#0,d0
	chkcnt	cnt_divz,1,9

	; 68040 long divide-by-zero clears C but preserves X/N/Z/V.
	; Use all CCR bits set so a stale C is observable after RTE.
	moveq	#0,d1
	move.l	#$142,d0
	move.w	#$1F,ccr
	divul.l	d1,d2:d0
	chkccr	$1E,64
	chkcnt	cnt_divz,2,65

	move.l	#$142,d0
	move.w	#$1F,ccr
	divu.w	#0,d0
	chkccr	$1E,66
	chkcnt	cnt_divz,3,67

;----------------------------------------------------------------- TRAPV / TRAPcc
	move.w	#$02,ccr
	trapv
	chkcnt	cnt_trapv,1,10
	move.w	#$00,ccr
	trapv
	chkcnt	cnt_trapv,1,11
	move.w	#$04,ccr	; Z=1
	trapeq
	chkcnt	cnt_trapv,2,12
	trapne
	chkcnt	cnt_trapv,2,13
	trapeq.w #$1234		; with operand word
	chkcnt	cnt_trapv,3,14

; (section 'trace' left out of the exc_m4 extract)

;----------------------------------------------------------------- MOVEC matrix
	moveq	#0,d0
	move.l	#$100,d0
	movec	d0,vbr
	movec	vbr,d1
	chkl	d1,$100,15
	moveq	#0,d0
	movec	d0,vbr		; vectors back at zero

	move.l	#$FFFFFFFF,d0
	movec	d0,sfc
	movec	sfc,d1
	chkl	d1,7,16
	movec	d0,dfc
	movec	dfc,d1
	chkl	d1,7,17

	movec	d0,cacr
	movec	cacr,d1
	chkl	d1,$80008000,18
	moveq	#0,d0
	movec	d0,cacr

	move.l	#$FFFF4000,d0	; P bit only: E stays off here
	movec	d0,tc
	movec	tc,d1
	chkl	d1,$00004000,19
	moveq	#0,d0
	movec	d0,tc

	move.l	#$FFFFFFFF,d0
	movec	d0,itt0
	movec	itt0,d1
	chkl	d1,$FFFFE364,20
	movec	d0,dtt1
	movec	dtt1,d1
	chkl	d1,$FFFFE364,21
	moveq	#0,d0
	movec	d0,itt0
	movec	d0,dtt1

	move.l	#$FFFFFFFF,d0
	movec	d0,urp
	movec	urp,d1
	chkl	d1,$FFFFFE00,22
	movec	d0,srp
	movec	srp,d1
	chkl	d1,$FFFFFE00,23

	move.l	#$12345678,d0
	movec	d0,mmusr
	movec	mmusr,d1
	chkl	d1,$12345678,24

	move.l	#$3C00,d0
	movec	d0,usp
	movec	usp,d1
	chkl	d1,$3C00,25

	move.l	#$3800,d0
	movec	d0,msp
	movec	msp,d1
	chkl	d1,$3800,26

	movec	isp,d0		; active stack: must equal SP
	cmp.l	sp,d0
	beq.s	t27ok
	failt	27
t27ok:

;----------------------------------------------------------------- MOVE USP
	movea.l	#$3C00,a0
	move	a0,usp
	move	usp,a1
	cmpa.l	#$3C00,a1
	beq.s	t28ok
	failt	28
t28ok:

;----------------------------------------------------------------- MOVES
	moveq	#1,d0
	movec	d0,sfc
	movec	d0,dfc
	lea	(FCREG).l,a0
	move.b	#$5A,d1
	moves.b	d1,(a0)		; TB verifies FC=1 on this write
	moves.b	(a0),d2
	and.l	#$FF,d2
	chkl	d2,$5A,29

; (section 'PTEST/PFLUSH/CINV/CPUSH decode' left out of the exc_m4 extract)

;----------------------------------------------------------------- user mode round trip
	movea.l	#$3C00,a0
	movec	a0,usp
	move.w	#$0000,-(sp)	; format/vector
	pea	user_code(pc)
	move.w	#$0000,-(sp)	; user SR
	rte

user_code:
	move.l	#$CAFEBABE,-(sp)	; goes to the user stack
	trap	#1
	move.w	#$2700,sr	; privilege violation in user mode
	failt	31		; never reached

super_cont:
	chkcnt	cnt_trapu,1,32
	chkcnt	cnt_priv,1,33

; (section 'format error' left out of the exc_m4 extract)

; (section 'address error' left out of the exc_m4 extract)

; (section 'interrupts' left out of the exc_m4 extract)

; (section 'M bit throwaway' left out of the exc_m4 extract)

; (section 'level-sensitive IPL: the NetBSD ports shape' left out of the exc_m4 extract)

;-------------------- immediate group: destination must be data alterable
; ORI/ANDI/SUBI/ADDI/EORI with a PC-relative or immediate destination are
; illegal; executing them instead consumes the following words as operands
; and runs off into the instruction stream (cputest 68040_default ILLEGAL).
; The handler resumes at the opcode + 2, so the words that would have been
; the operands are NOPs here.  CMPI is the exception the 68020 added: it
; may read program space, and must not trap.
	clr.w	(cnt_ill).l
	dc.w	$003A,$4E71,$4E71	; ori.b  #x,(d16,pc)
	chkcnt	cnt_ill,1,70
	dc.w	$023A,$4E71,$4E71	; andi.b #x,(d16,pc)
	chkcnt	cnt_ill,2,71
	dc.w	$043A,$4E71,$4E71	; subi.b #x,(d16,pc)
	chkcnt	cnt_ill,3,72
	dc.w	$063A,$4E71,$4E71	; addi.b #x,(d16,pc)
	chkcnt	cnt_ill,4,73
	dc.w	$0A3A,$4E71,$4E71	; eori.b #x,(d16,pc)
	chkcnt	cnt_ill,5,74
	dc.w	$043C,$4E71		; subi.b #x,#imm: no CCR form exists
	chkcnt	cnt_ill,6,75
	dc.w	$0C3C,$4E71		; cmpi.b #x,#imm: immediate is not a source
	chkcnt	cnt_ill,7,76

; static bit ops: BCHG/BCLR/BSET need a data alterable destination, while
; BTST may read program space and even an immediate operand
	dc.w	$08BA,$0000,$4E71	; bclr #0,(d16,pc)
	chkcnt	cnt_ill,8,78
	dc.w	$08FA,$0000,$4E71	; bset #0,(d16,pc)
	chkcnt	cnt_ill,9,79
	dc.w	$0849,$4E71		; bchg #x,a1: an address register is illegal
	chkcnt	cnt_ill,10,80
	btst	#0,bittgt(pc)		; BTST may read program space
	chkcnt	cnt_ill,10,81
	dc.w	$017A,$0000,$4E71	; bchg d0,(d16,pc)
	chkcnt	cnt_ill,11,111
	dc.w	$01BA,$0000,$4E71	; bclr d0,(d16,pc)
	chkcnt	cnt_ill,12,112
	dc.w	$01FA,$0000,$4E71	; bset d0,(d16,pc)
	chkcnt	cnt_ill,13,113
	dc.w	$813A,$4E71		; or.b  d0,(d16,pc)
	chkcnt	cnt_ill,14,115
	dc.w	$913A,$4E71		; sub.b d0,(d16,pc)
	chkcnt	cnt_ill,15,116
	dc.w	$B13A,$4E71		; eor.b d0,(d16,pc)
	chkcnt	cnt_ill,16,117
	dc.w	$C13A,$4E71		; and.b d0,(d16,pc)
	chkcnt	cnt_ill,17,118
	dc.w	$D13A,$4E71		; add.b d0,(d16,pc)
	chkcnt	cnt_ill,18,119
	subq.w	#8,(cnt_ill).l
					; keep the legacy counter sequence below
	bra.s	bitok
bittgt:
	dc.b	0,0
bitok:

; single-operand writes also need a data alterable destination
	dc.w	$42BA,$4E71		; clr.l (d16,pc)
	chkcnt	cnt_ill,11,83
	dc.w	$4AFA,$4E71		; tas (d16,pc)
	chkcnt	cnt_ill,12,84
	dc.w	$403A,$4E71		; negx.b (d16,pc)
	chkcnt	cnt_ill,13,106
	dc.w	$443A,$4E71		; neg.b (d16,pc)
	chkcnt	cnt_ill,14,107
	dc.w	$463A,$4E71		; not.b (d16,pc)
	chkcnt	cnt_ill,15,108
	dc.w	$483A,$4E71		; nbcd (d16,pc)
	chkcnt	cnt_ill,16,109
	dc.w	$40FA,$4E71		; move sr,(d16,pc)
	chkcnt	cnt_ill,17,110
	dc.w	$42FA,$4E71		; move ccr,(d16,pc)
	chkcnt	cnt_ill,18,111

; Bit 8 is fixed clear in the unary/MOVEM subfamilies below.  The reserved
; aliases must not fall through by looking only at the size bits.
	dc.w	$4140			; reserved alias of negx.w d0
	chkcnt	cnt_ill,19,120
	dc.w	$4340			; reserved alias of clr.w d0
	chkcnt	cnt_ill,20,121
	dc.w	$4540			; reserved alias of neg.w d0
	chkcnt	cnt_ill,21,122
	dc.w	$4740			; reserved alias of not.w d0
	chkcnt	cnt_ill,22,123
	dc.w	$4908,$4E71,$4E71	; must not decode as link.l a0,#imm32
	chkcnt	cnt_ill,23,124
	dc.w	$4B40			; reserved alias of tst.w d0
	chkcnt	cnt_ill,24,125
	dc.w	$4D40,$4E71		; must not decode as divl + extension
	chkcnt	cnt_ill,25,126

; Reserved mode-7 source registers and PC-relative quick destinations are
; encoding errors, including when a privileged SR operation is attempted.
	dc.w	$46FE			; move <reserved>,sr
	chkcnt	cnt_ill,26,127
	dc.w	$42FE			; move <reserved>,ccr
	chkcnt	cnt_ill,27,128
	dc.w	$503A,$4E71		; addq.b #8,(d16,pc)
	chkcnt	cnt_ill,28,129
	; (Scc with a PC-relative encoding does not exist: mode 111 reg 010,
	; 011 and 100 are TRAPcc on the 68020 and later, and are legal.)
	tst.l	tsttgt(pc)		; TST may read program space on 020+
	chkcnt	cnt_ill,28,85
	bra.s	tstok
tsttgt:
	dc.l	0
tstok:

; CMPI against program space is legal on the 68040 and must not trap
	moveq	#0,d0
	cmpi.b	#0,cmpitgt(pc)
	chkcnt	cnt_ill,28,77
	bra.s	cmpiok
cmpitgt:
	dc.b	0,0
cmpiok:

; (section 'physical bus error' left out of the exc_m4 extract)

;----------------------------------------------------------------- all done
	move.w	#$600D,(DONEREG).l
halt:
	bra.s	halt

;----------------------------------------------------------------- wait loops
wait_int2_1:
	move.l	#20000,d0
wi21:
	move.w	(cnt_int2).l,d1
	cmp.w	#1,d1
	beq.s	wi2done
	subq.l	#1,d0
	bne.s	wi21
	failt	50
wi2done:
	rts

wait_int2_3:
	move.l	#20000,d0
wi23:
	move.w	(cnt_int2).l,d1
	cmp.w	#3,d1
	beq.s	wi2done
	subq.l	#1,d0
	bne.s	wi23
	failt	51

wait_int5_1:
	move.l	#20000,d0
wi51:
	move.w	(cnt_int5).l,d1
	cmp.w	#1,d1
	beq.s	wi5done
	subq.l	#1,d0
	bne.s	wi51
	failt	52
wi5done:
	rts

wait_nmi_1:
	move.l	#20000,d0
wn1:
	move.w	(cnt_nmi).l,d1
	cmp.w	#1,d1
	beq.s	wndone
	subq.l	#1,d0
	bne.s	wn1
	failt	53
wndone:
	rts

wait_nmi_2:
	move.l	#20000,d0
wn2:
	move.w	(cnt_nmi).l,d1
	cmp.w	#2,d1
	beq.s	wndone
	subq.l	#1,d0
	bne.s	wn2
	failt	54

;----------------------------------------------------------------- handlers
h_trap0:
	move.w	#1,(hid).l	; X2.3a: identify the handler for hfail
	move.w	#1,(trap_guard).l	; deliberately the first handler instruction
	cmpi.w	#$0080,6(sp)
	bne	hfail
	addq.w	#1,(cnt_trap0).l
	rte

h_trap1:
	move.w	#2,(hid).l	; X2.3a: identify the handler for hfail
	; arrived from user mode: check stacked SR, USP and user stack data
	move.l	d0,-(sp)
	move.w	4(sp),d0	; stacked SR
	andi.w	#$2000,d0
	bne	hfail
	movec	usp,d0
	cmp.l	#$3BFC,d0
	bne	hfail
	move.l	($3BFC).l,d0
	cmp.l	#$CAFEBABE,d0
	bne	hfail
	addq.w	#1,(cnt_trapu).l
	move.l	(sp)+,d0
	rte

h_ill:
	move.w	#3,(hid).l	; X2.3a: identify the handler for hfail
	cmpi.w	#$0010,6(sp)
	bne	hfail
	addq.l	#2,2(sp)	; skip the 2-byte opcode
	addq.w	#1,(cnt_ill).l
	rte

h_aline:
	move.w	#4,(hid).l	; X2.3a: identify the handler for hfail
	cmpi.w	#$0028,6(sp)
	bne	hfail
	addq.l	#2,2(sp)
	addq.w	#1,(cnt_aline).l
	rte

h_fline:
	move.w	#5,(hid).l	; X2.3a: identify the handler for hfail
	cmpi.w	#$002C,6(sp)
	bne	hfail
	addq.l	#2,2(sp)
	addq.w	#1,(cnt_fline).l
	rte

h_chk:
	move.w	#6,(hid).l	; X2.3a: identify the handler for hfail
	cmpi.w	#$2018,6(sp)
	bne	hfail
	addq.w	#1,(cnt_chk).l
	rte

h_divz:
	move.w	#7,(hid).l	; X2.3a: identify the handler for hfail
	cmpi.w	#$2014,6(sp)
	bne	hfail
	addq.w	#1,(cnt_divz).l
	rte

h_trapv:
	move.w	#8,(hid).l	; X2.3a: identify the handler for hfail
	cmpi.w	#$201C,6(sp)
	bne	hfail
	addq.w	#1,(cnt_trapv).l
	rte

h_trace:
	move.w	#9,(hid).l	; X2.3a: identify the handler for hfail
	cmpi.w	#$2024,6(sp)	; format $2, vector 9
	bne	hfail
	tst.l	(trace_pc).l	; capture the FIRST trace since the clear
	bne.s	ht_nocap
	move.l	2(sp),(trace_pc).l
ht_nocap:
	andi.w	#$3FFF,(sp)	; stop tracing on return
	addq.w	#1,(cnt_trace).l
	rte

h_priv:
	move.w	#10,(hid).l	; X2.3a: identify the handler for hfail
	cmpi.w	#$0020,6(sp)
	bne	hfail
	ori.w	#$2000,(sp)	; return in supervisor mode
	move.l	#super_cont,2(sp)
	addq.w	#1,(cnt_priv).l
	rte

h_fmt:
	move.w	#11,(hid).l	; X2.3a: identify the handler for hfail
	cmpi.w	#$0038,6(sp)
	bne	hfail
	move.l	(resume).l,2(sp)
	addq.w	#1,(cnt_fmt).l
	rte

h_addr:
	move.w	#12,(hid).l	; X2.3a: identify the handler for hfail
	move.l	sp,(got_fsp).l	; frame base, for SP-preservation checks
	cmpi.w	#$200C,6(sp)
	bne	hfail
	move.l	8(sp),d6
	cmp.l	(exp_addr).l,d6
	bne	hfail
	move.l	2(sp),d6
	cmp.l	(exp_pc).l,d6
	bne	hfail
	tst.w	(exp_srv).l
	beq.s	haddr_noexact
	move.w	(sp),d6		; exact stacked-SR compare (RTE/RTR odd-PC
	cmp.w	(exp_sr).l,d6	; commits restored SR / popped CCR first)
	bne	hfail
	clr.w	(exp_srv).l
	andi.w	#$3FFF,(sp)	; resume the test without the restored trace bits
	ori.w	#$2000,(sp)	; and on the supervisor stack/context
	bra.s	haddr_sr_ok
haddr_noexact:
	tst.w	(addr_sflag).l
	beq.s	haddr_sr_ok
	move.w	(sp),d6
	andi.w	#$2000,d6
	beq	hfail
	andi.w	#$3FFF,(sp)	; clear restored trace bits
	clr.w	(addr_sflag).l
haddr_sr_ok:
	move.l	(resume).l,2(sp)
	addq.w	#1,(cnt_addr).l
	rte

h_buserr:
	move.w	#13,(hid).l	; X2.3a: identify the handler for hfail
	move.l	$14(sp),(hfa).l	; X2.3a: record the fault address for hfail
	move.l	2(sp),(hfpc).l
	cmpi.w	#$7008,6(sp)	; format $7, vector 2
	bne	hfail
	move.l	$14(sp),d0	; fault address
	cmp.l	(fberr_fa).l,d0	; the armed FETCH berr address?
	beq.s	hb_fetch
	cmpi.l	#(FCREG+$20),d0
	bne	hfail
	move.w	$0C(sp),d0	; SSW
	andi.w	#$0400,d0	; ATC fault must be clear for physical berr
	bne	hfail
	move.w	$0C(sp),d0
	andi.w	#7,d0		; supervisor data FC
	cmp.w	(buserr_fc).l,d0
	bne	hfail
	addq.w	#1,(cnt_buserr).l
	rte

hb_fetch:
	move.w	$0C(sp),d0	; SSW
	andi.w	#$0400,d0	; ATC clear: physical berr
	bne	hfail
	move.w	$0C(sp),d0
	andi.w	#7,d0		; supervisor program space
	cmp.w	#6,d0
	bne	hfail
	addq.w	#1,(cnt_fberr).l
	rte

h_int2:
	move.w	#14,(hid).l	; X2.3a: identify the handler for hfail
	move.l	d0,-(sp)
	move.l	6(sp),(int2_pc).l
	tst.w	(kick5).l	; nested-service test: a level-5 device
	beq.s	hi2nokick	; asserts while level 2 is in service
	clr.w	(kick5).l
	move.w	#5,(IPLREG).l
hi2nokick:
	tst.w	(irq_exc).l
	beq.s	hi2exc_ok
	tst.w	(trap_guard).l	; original TRAP handler must not have begun
	bne	hfail
	clr.w	(irq_exc).l
hi2exc_ok:
	tst.w	(irq_early).l
	beq.s	hi2early_ok
	tst.w	(irq_guard).l	; RTE takes the request AT its own boundary, so
	bne	hfail		; the restored instruction has NOT run yet
	tst.w	(irq_guard2).l
	bne	hfail
	clr.w	(irq_early).l
hi2early_ok:
	move.w	10(sp),d0	; frame format/vector
	andi.w	#$0FFF,d0
	cmpi.w	#$0068,d0
	bne	hfail
	move.w	10(sp),d0
	andi.w	#$F000,d0
	beq.s	hi2f0
	cmpi.w	#$1000,d0
	bne	hfail
	move.w	4(sp),d0	; capture the throwaway SR image (d0 is
	move.w	d0,(tw_sr).l	; pushed at entry, frame starts at 4(sp))
	addq.w	#1,(cnt_mflag).l
	move.w	sr,d0		; M must already be clear on a throwaway
	andi.w	#$1000,d0
	bne	hfail
hi2f0:
	addq.w	#1,(cnt_int2).l
	tst.w	(hold2).l	; level-sensitivity test: the device is NOT
	beq.s	hi2clr		; acknowledged -- the line stays asserted
	subq.w	#1,(hold2).l	; through the RTE and must be taken again
	bra.s	hi2held
hi2clr:
	move.w	#0,(IPLREG).l
hi2held:
	move.l	(sp)+,d0
	rte

h_int3:
	move.w	#15,(hid).l	; X2.3a: identify the handler for hfail
	cmpi.w	#$006C,6(sp)
	bne	hfail
	addq.w	#1,(cnt_int3).l
	move.w	#0,(IPLREG).l
	rte

h_int5:
	move.w	#16,(hid).l	; X2.3a: identify the handler for hfail
	cmpi.w	#$0074,6(sp)
	bne	hfail
	addq.w	#1,(cnt_int5).l
	tst.w	(nest52).l	; nested-service test: only the level-5
	beq.s	hi5clr		; device is cleared; the level-2 request
	clr.w	(nest52).l	; below it is still standing
	move.w	#2,(IPLREG).l
	rte
hi5clr:
	move.w	#0,(IPLREG).l
	rte

h_nmi:
	move.w	#17,(hid).l	; X2.3a: identify the handler for hfail
	cmpi.w	#$007C,6(sp)
	bne	hfail
	addq.w	#1,(cnt_nmi).l
	move.w	#0,(IPLREG).l
	rte

hfail:
	; hid names the handler that rejected something; the testbench prints
	; it, so a timing shift no longer produces an anonymous "test 98".
	failt	98

fail_all:
	move.w	d7,(FAILREG).l
	move.w	#$BAD0,(DONEREG).l
halt1:
	bra.s	halt1

unexp:
	move.w	#$0099,(FAILREG).l
	move.w	#$BAD0,(DONEREG).l
halt2:
	bra.s	halt2

