; diff: --cycles 60000
; expect-mem: m16 f100 m16 f102
; Generated by mk_tint.py m2 from /home/paul/work/fpga/Xilinx/artix7/MinimigAGA_TC64/lib/AP68040/tb/asm/t_integer.s -- do not edit
; AP040 milestone C integer ISA self test
; assembled with vasmm68k_mot -Fbin -m68040
;
; protocol with the testbench:
;   word write to $F100 = failing test number
;   word write to $F102 = $BAD0 on failure, $600D when all tests passed
;
; the program is fully self checking; expected values are encoded inline

FAILREG	equ	$F100
DONEREG	equ	$F102

; fail with test number \1
failt	macro
	move.w	#\1,d7
	bra	fail_all
	endm

; compare register \1 (long) against \2, fail with number \3
chkl	macro
	cmp.l	#\2,\1
	beq.s	ok\@
	failt	\3
ok\@:
	endm

; compare CCR (via MOVE from CCR) against \1, fail with number \2
chkccr	macro
	move.w	ccr,d6
	andi.w	#$1F,d6
	cmp.w	#\1,d6
	beq.s	ok\@
	failt	\2
ok\@:
	endm

	org	0
	dc.l	$3400		; initial ISP
	dc.l	start		; initial PC
	rept	254
	dc.l	unexp		; vectors 2-255: unexpected
	endr

	org	$400
start:
;------------------------------------------------- run cache-hot (P1)
; The whole integer battery executes with both internal caches enabled:
; every test after this point doubles as I/D-cache-hit coverage.  The
; caches are write-through with invalidate-on-write, so no test below
; needs cache maintenance.
	move.l	#$80008000,d0
	movec	d0,cacr

;----------------------------------------------------------------- moveq
	moveq	#-1,d0
	chkl	d0,$FFFFFFFF,1
	moveq	#0,d0
	chkccr	$04,2		; Z only

;----------------------------------------------------------------- add/sub flags
	move.l	#$7FFFFFFF,d0
	add.l	#1,d0
	chkccr	$0A,3		; N V
	chkl	d0,$80000000,4

	moveq	#0,d0
	subq.l	#1,d0
	chkccr	$19,5		; X N C
	chkl	d0,$FFFFFFFF,6

	move.w	#$FFFF,d0
	add.w	#1,d0
	chkccr	$15,7		; X Z C (word wraps to 0)

;----------------------------------------------------------------- addx/subx
	move.w	#$14,ccr	; X=1 Z=1
	moveq	#0,d0
	moveq	#0,d1
	addx.l	d1,d0
	chkccr	$00,9		; result nonzero clears sticky Z
	chkl	d0,1,8

	move.w	#$04,ccr	; X=0 Z=1
	moveq	#0,d1
	moveq	#0,d2
	addx.l	d2,d1
	chkccr	$04,10		; zero result keeps sticky Z

	move.w	#$10,ccr	; X=1 Z=0
	moveq	#0,d0
	negx.l	d0
	chkccr	$19,12		; X N C
	chkl	d0,$FFFFFFFF,11

;----------------------------------------------------------------- logic
	move.w	#0,ccr
	move.l	#$F0F0F0F0,d0
	and.l	#$0FF00FF0,d0
	chkl	d0,$00F000F0,13
	or.l	#$0F000F00,d0
	chkl	d0,$0FF00FF0,14
	eor.l	#$FFFFFFFF,d0
	chkl	d0,$F00FF00F,15
	not.l	d0
	chkl	d0,$0FF00FF0,16
	move.w	#0,ccr
	clr.l	d0
	chkccr	$04,17

;----------------------------------------------------------------- neg
	move.w	#0,ccr
	move.l	#1,d0
	neg.l	d0
	chkccr	$19,19
	chkl	d0,$FFFFFFFF,18
	move.b	#$80,d0
	neg.b	d0
	chkccr	$1B,20		; X N V C for byte $80

; (section 'shifts' left out of the m2 extract)

; (section 'bit ops' left out of the m2 extract)

; (section 'word mul/div' left out of the m2 extract)

; (section 'long mul/div' left out of the m2 extract)

; (section 'BCD' left out of the m2 extract)

;----------------------------------------------------------------- ext/swap/exg
	move.l	#$80,d0
	ext.w	d0
	chkl	d0,$FF80,60
	ext.l	d0
	chkl	d0,$FFFFFF80,61
	move.l	#$80,d1
	extb.l	d1
	chkl	d1,$FFFFFF80,62
	move.l	#$12345678,d2
	swap	d2
	chkl	d2,$56781234,63
	move.l	#$11111111,d0
	move.l	#$22222222,d1
	exg	d0,d1
	chkl	d0,$22222222,64
	chkl	d1,$11111111,65
	movea.l	#$33333333,a1
	exg	d0,a1
	chkl	d0,$33333333,66

;----------------------------------------------------------------- EA modes
	lea	($3000).l,a0
	move.l	#$AABBCCDD,(a0)
	move.l	(a0),d0
	chkl	d0,$AABBCCDD,67
	move.l	#$11112222,4(a0)
	moveq	#4,d1
	move.l	(0,a0,d1.w),d2
	chkl	d2,$11112222,68
	move.l	#$33334444,8(a0)
	move.l	(0,a0,d1.w*2),d2
	chkl	d2,$33334444,69
	move.l	#$55556666,$20(a0)
	move.l	($10,a0,d1.l*4),d3
	chkl	d3,$55556666,70

	; memory indirect pre-indexed: ([$40,a0],4)
	move.l	#$3050,($3040).l
	move.l	#$DEAD0001,($3054).l
	move.l	([$40,a0],4),d4
	chkl	d4,$DEAD0001,71

	; memory indirect post-indexed: ([$40,a0],d1.l*2,4) = $3050+8+4
	move.l	#$DEAD0002,($305C).l
	move.l	([$40,a0],d1.l*2,4),d5
	chkl	d5,$DEAD0002,72

	; PC relative
	move.l	tdata(pc),d6
	chkl	d6,$0BADCAFE,73
	moveq	#4,d2
	move.l	(tdata,pc,d2.l),d6
	chkl	d6,$0BADF00D,74

	; absolute short
	move.w	#$1234,($3000).w
	move.w	($3000).w,d0
	and.l	#$FFFF,d0
	chkl	d0,$1234,75

;----------------------------------------------------------------- adda/cmpa
	movea.l	#$10000,a5
	adda.w	#$8000,a5	; sign extends
	cmpa.l	#$8000,a5
	beq.s	t76ok
	failt	76
t76ok:
	movea.l	#-1,a5
	cmpa.w	#$FFFF,a5	; sign extended compare equal
	beq.s	t77ok
	failt	77
t77ok:
	suba.l	a5,a5
	cmpa.l	#0,a5
	beq.s	t78ok
	failt	78
t78ok:

;----------------------------------------------------------------- addq/subq to An
	movea.l	#$1000,a4
	addq.w	#5,a4		; whole register
	subq.l	#1,a4
	cmpa.l	#$1004,a4
	beq.s	t79ok
	failt	79
t79ok:

;----------------------------------------------------------------- control flow
	moveq	#0,d0
	bsr	sub1
	chkl	d0,1,80
	lea	sub1(pc),a2
	jsr	(a2)
	chkl	d0,2,81

	move.l	sp,d5		; sp checkpoints for link/unlk
	link	a6,#-16
	unlk	a6
	cmp.l	sp,d5
	beq.s	t82ok
	failt	82
t82ok:
	link.l	a6,#-$10000
	unlk	a6
	cmp.l	sp,d5
	beq.s	t83ok
	failt	83
t83ok:

	pea	4(a0)
	move.l	(sp)+,d0
	move.l	a0,d1
	addq.l	#4,d1
	cmp.l	d0,d1
	beq.s	t84ok
	failt	84
t84ok:

	moveq	#3,d0
	moveq	#0,d1
dbloop:
	addq.l	#1,d1
	dbra	d0,dbloop
	chkl	d1,4,85
	chkl	d0,$FFFF,86

	cmp.l	d1,d1
	seq	d2
	sne	d3
	and.l	#$FF,d2
	chkl	d2,$FF,87
	and.l	#$FF,d3
	chkl	d3,0,88

	; rtd
	move.l	sp,d5
	pea	($12345678).l	; junk long the callee will discard
	bsr	subrtd
	cmp.l	sp,d5
	beq.s	t89ok
	failt	89
t89ok:

	; cmpm
	lea	($3060).l,a0
	lea	($3064).l,a1
	move.w	#$5555,(a0)
	move.w	#$5555,(a1)
	cmpm.w	(a0)+,(a1)+
	beq.s	t90ok
	failt	90
t90ok:
	move.l	a0,d0
	chkl	d0,$3062,91

; (block '; tas' left out of the m2 extract)

; (section 'movem' left out of the m2 extract)

; (section 'movep' left out of the m2 extract)

; (section 'pack/unpk' left out of the m2 extract)

; (section 'move16' left out of the m2 extract)

;----------------------------------------------------------------- ccr moves
	move.w	#$1F,ccr
	move.w	ccr,d0
	and.l	#$FF,d0
	chkl	d0,$1F,107
	move.w	#$04,ccr
	move.w	ccr,d0
	and.l	#$FF,d0
	chkl	d0,$04,108

;----------------------------------------------------------------- tst
	suba.l	a4,a4
	tst.w	a4
	chkccr	$04,109
	move.l	#$80000000,d0
	tst.l	d0
	chkccr	$08,110
	clr.w	($3004).l
	tst.w	($3004).l
	chkccr	$04,111

; (section 'bitfields' left out of the m2 extract)

; (section 'CAS' left out of the m2 extract)

; (section 'BTST Dn,#imm and CMP2' left out of the m2 extract)

; (section 'CAS2' left out of the m2 extract)

; (section 'BCD with' left out of the m2 extract)

; (section 'CHK flags' left out of the m2 extract)

; (section 'DIVS.L 32-bit overflow' left out of the m2 extract)

; (section 'MULx.L with Dh == Dl' left out of the m2 extract)

; (section 'shift/rotate count edges' left out of the m2 extract)

; (section 'MOVEM predec with base reg in list' left out of the m2 extract)

; (section 'store into the fetch queue' left out of the m2 extract)

;----------------------------------------------------------------- all done
	move.w	#$600D,(DONEREG).l
halt:
	bra.s	halt

;----------------------------------------------------------------- helpers
sub1:
	addq.l	#1,d0
	rts

subrtd:
	rtd	#4

fail_all:
	move.w	d7,(FAILREG).l
	move.w	#$BAD0,(DONEREG).l
halt1:
	bra.s	halt1

unexp:
	move.w	#$00FF,(FAILREG).l
	move.w	#$BAD0,(DONEREG).l
halt2:
	bra.s	halt2

	even
tdata:
	dc.l	$0BADCAFE
	dc.l	$0BADF00D

